# Objects in Linear Algebra

Commonly encountered objects and calculations in Linear Algebra, implemented in Python.

Sources:
- [Python Numerical Methods: Basics of Linear Algebra](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter14.01-Basics-of-Linear-Algebra.html)
- https://en.wikipedia.org/wiki/Matrix_multiplication
- https://en.wikipedia.org/wiki/Dot_product
- https://en.wikipedia.org/wiki/Cross_product
- https://en.wikipedia.org/wiki/Hadamard_product_(matrices)
- https://en.wikipedia.org/wiki/Tensor_product

## 0. Key Takeaways:

### 0.1. Syntax 

- To define vectors and matrices in NumPy, use `np.array([[]])` with double square brackets
    - A row vector: `[[ csv row elements ]]`
    - A column vector: `[[elem 1], [elem 2], elem 3]]`, and you can put each on a new line
    - A matrix: ``[[ csv row 1], [ csv row 2], ...]``, and you can put each on a new line

### 0.2. Concepts covered
- Basics set notation
- Vectors 
    - Definition and properties (transpose, length `norm`s)
    - Addition
    - Multiplication (scalar, dot, and cross product)
    - Angle between 2 vectors (via dot product)
- Matrices
    - <mark>A matrix is simply an object which transforms space linearly</mark>
    - Definition and properties (transpose, length `norm`s)
    - Addition and scalar multiplication
    - Matrix multiplication (using `np.dot`) - inner dimensions must match
        - *NB: A vector is just a matrix with 1 column (or row if it's a row vector)*
    - Square matrices
        - **Determinant**
        - May be **invertible** (if $AA^{-1}=I)$:
            - **Singular** (non-invertible) matrix if $det(A) = 0$
                - Ill-conditioned if determinant is *close to 0* (**high** condition number = **more** singular)
            - **Non-singular** (invertible) matrix if $det(A) \ne 0$
        - **Rank**: the number of linearly independent columns in the matrix)
        - **Trace**: the sum of on-diagonal elements
        - Identity Matrix
        - Augmented matrix (concatenating a vector $y$ to a matrix $A$ to give $[A,y]$)


## List of functions left to write

- Masks (e.g. lower triangle, upper triangle and identity)
- Basic identities (e.g. LU decomposition and the other commonly used ones, $Z^TZ$ etc, $A^TAI$)

## Open questions:
- What is the interpretation, and general point of determinant, trace and rank?
- Why do we care about full-rank? Is it somehow better?
- $\text{det}(M_1 M_2) = \text{det}(M_1) \text{det}(M_2)$
- Explain the geometric intuition behind a determinant

In [1]:
import numpy as np  # more basic functionality


## 1. Set Notation

- A collection of objects (objects are denoted in braces {})
    - **Empty set** (denoted $\{\}$ or $\emptyset$): the set containing no objects)
- Common set operations:
    - **Union**, $A \cup B$: Set containing all elements of $A$ **or** $B$
    - **Intersection**, $A \cap B$: Set containing all elements that belong to **both** $A$ **and** $B$
    - **Proper/strict subset**, $C \subset A$: $C$ is a strict subset of (i.e. included in; **but is not equal** to) $A$
        - **Subset**, $C\subseteq A$: $C$ is a subset of (i.e. included in; **or is equal** to) $A$
    - **Proper/strict superset**, $C \supset A$: $C$ is a strict superset of (i.e. includes; **but is not equal** to) $A$
        - **Superset**, $C\supseteq A$: $C$ is a superset of (i.e. includes; **or is equal** to) $A$
    - **Relative complement**: 
    - Colon ($:$) means "**such that**"
    - $a\in A$ means "element $a$ is a member of set $A$"
    - Backslash ($\backslash$) means ""**set minus**" so if $a\in A$, then  $A\backslash a$ means "$A$ minus the element $a$"
- Some standard sets related to numbers: 
    - Naturals: $\mathbb{N} = \{1, 2, 3, 4, \cdots\}$
    - Wholes: $\mathbb{W} = \mathbb{N} \cup \{0\}$
    - Integers: $\mathbb{Z} = \mathbb{W} \cup \{-1, -2, -3, \cdots\}$
    - Rationals: $\mathbb{Q} =  \{\frac{p}{q} : p\in {\mathbb{Z}}, q\in {\mathbb{Z}} \backslash \{0\}\}$
    - Irrationals: $\mathbb{I}$ is the set of real numbers not expressible as a fraction of integers
    - Reals: $\mathbb{R} = \mathbb{Q} \cup \mathbb{I}$
    - Complex numbers: $\mathbb{C} = \{a + bi : a,b\in {\mathbb{R}}, i = \sqrt{-1}\}$
- Example:
    - Let $S$ be the set of all real $(x,y)$ pairs such that $x^2 + y^2 = 1$ Write $S$ using set notation:
    - $S = \{(x,y) : x,y \in {\mathbb{R}}, x^2 + y^2 = 1\}$


## 2. Vectors

### Properties of a vector $\mathbf{v}$:
- $i$'th element: $v_i$
- Transpose (turns columns into rows and vice versa): $\mathbf{v}^\mathrm{T}$ (for a matrix it swaps rows with columns)
    - By convention, vectors are implicitly column vectors. Hence, to represent $\mathbf{v}$ as a row vector, we denote its transposed form: $\mathbf{v}^\mathrm{T}$.
- Length (many definitions (distance formulas) we can use):
    - $L_2$ norm (Euclidian length): $\Vert\mathbf{v}\Vert_2 = \sqrt{\Sigma_i v_{i}^{2}}\quad$ (*physical length* of a vector in n-dim space)
    - $L_1$ norm (Manhattan Distance): $\Vert\mathbf{v}\Vert_1 = \Sigma_i |v_i|\quad $
    - More generally, 
        - The **p-norm** is $\Vert v \Vert_{p} = \sqrt[p]{(\sum_i v_i^p)}$
        - And the $L_\infty$ norm, $\Vert\mathbf{v}\Vert_\infty$, is the $p$-norm where $p=\infty$
- Generally the $L_2$ norm is implied when referring to vector length. 
  - Hence $\Vert\mathbf{v}\Vert_2$ can be written more simply as $\Vert\mathbf{v}\Vert$ or occasionally $|\mathbf{v}|$ (though the latter is ambiguous with the absolute value of a scalar)

In [2]:
# Create a row vector and a column vector, show their shapes
row_vec = np.array([[1, -5, 3, 2, 4]])
col_vec = np.array([[1], [2], [3], [4]])

# Comments show output if you don't use list of lists
print(row_vec[0])  # [ 1 -5  3  2  4]
print(col_vec)  # [1 2 3 4]
print(row_vec.shape)  # (5,)
print(col_vec.shape)  # (4,)


[ 1 -5  3  2  4]
[[1]
 [2]
 [3]
 [4]]
(1, 5)
(4, 1)


In [3]:
# Transpose row_vec and calculate L1, L2, and L_inf norms
from numpy.linalg import norm

transposed_row_vec = row_vec.T  # now a column vector
print(transposed_row_vec)

norm_1 = norm(transposed_row_vec, 1)
norm_2 = norm(transposed_row_vec, 2)  # <- L2 norm is default and most common
norm_inf = norm(transposed_row_vec, np.inf)

print(f"L_1 is: {norm_1:.1f}")
print(f"L_2 is: {norm_2:.1f}")
print(f"L_inf is: {norm_inf:.1f}")  # NB: norm_inf = |largest element|


[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


## 3. Vector addition, $\mathbf{v} + \mathbf{w}$

Elementwise addition; if vectors are of of same length (i.e. if $\mathbf{v}$ and $\mathbf{w}$ are both in $\mathbb{R}^n$) then:

- **Addition of 2 vectors**: $\mathbf{u} = \mathbf{v} + \mathbf{w}$ is the vector with elements $u_i = v_i + w_i$


In [4]:
# Sum vectors v = [10, 9, 3] and w = [2, 5, 12]
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
u = v + w

print("Vector addition: \nv + w =", u[0])


Vector addition: 
v + w = [12 14 15]


## 4. Scalar-vector multiplication, $\alpha\mathbf{v}$

To multiply a vector $\mathbf{v}$, by a scalar $\alpha$ (a number in $\mathbb{R}$), do it "elementwise" or "pairwise".

- **Scalar multiplication of a vector**: $\mathbf{u} = \alpha \mathbf{v}$ is the vector with elements $u_i = \alpha v_i$

In [5]:
# Multiply vector v = [10, 9, 3] by scalar alpha = 4
v = np.array([[10, 9, 3]])
alpha = 4
u = alpha * v

print("Scalar vector multiplication: \nalpha * v =", u[0])


Scalar vector multiplication: 
alpha * v = [40 36 12]


### 4.1. Linear Combinations

- A **linear combination** of set $S$ is defined as $\Sigma \alpha_i s_i$
    - Here $\alpha_i$ values are the **coefficients** of $s_i$ values
    - Example: Grocery bill total cost is a linear combination of items purchased:
        - $\displaystyle{\sum c_i n_i}$ ($c_i$ is item cost, $n_i$ is qty. purchased)
    
### 4.2. Linear Dependence and Independence
    
- A set is **linearly INdependent** if no object in the set can be written as a lin. combination of the other objects in the set.
    - Example: $\mathbf{v} = [1, 1, 0], \mathbf{w} = [1, 0, 0]$ and $\mathbf{u} = [0, 0, 1]$ are <mark>linearly independent. Can you see why?</mark>
- Below is an example of a **linearly DEpendent** set. $\mathbf{x}$ is dependent on 

In [6]:
# Writing the vector x = [-8, -1, 4] as a linear combination of 3 vectors, v, w, and u:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])

x = 3 * v - 2 * w + 4 * u
print("x is a linear combination of v, w, and u. It is linearly dependent on them: \nx =", x[0])


x is a linear combination of v, w, and u. It is linearly dependent on them: 
x = [-8 -1  4]


## 5. Vector-vector multiplication (3 approaches)

### 5.1. Vector dot product, $\mathbf{v} \cdot \mathbf{w}$ (i.e. commonly "vector times vector")

Geometric interpretation: <mark>A measure of how similarly directed two vectors are</mark>

- Definition: $\mathbf{v} \cdot \mathbf{w} = \Sigma_{i=1}^n v_i w_i$
    - It's the sum of elementwise products. For $\mathbf{v}, \mathbf{w} \in \mathbb{R}^n$, 
- Note also, since $\mathbf{v}, \mathbf{w} \in \mathbb{R}^n$, transpose to make inner dimensions match. Dot product can hence be rewritten as:
    - $\mathbf{v} \cdot \mathbf{w} = \mathbf{v}^\mathrm{T}\mathbf{w}$

#### Angle between vectors, $\theta$

- Think of dot product as "**degree of alignment**": $\mathbf{v} \cdot \mathbf{w} = \Vert\mathbf{v}\Vert\:\Vert\mathbf{w}\Vert \cos \theta$
    - (1,1) and (2,2) are **parallel**; computing the angle gives $\theta = 0$
    - (1,1) and (-1,1) are **orthogonal** (perpendicular) bc $\theta = \pi/2$ and $\mathbf{v} \cdot \mathbf{w} = 0$ (no alignment)

* Extending on the dot product idea, $\mathbf{v} \cdot \mathbf{w}$, the **angle between two vectors** is $\theta$. It is as defined by the formula:
$$ \theta = \arccos \left({\frac {\mathbf{v} \cdot \mathbf{w}}{\left\|\mathbf{v}\right\|\left\|\mathbf{w} \right\|}}\right) $$

#### Recap: Many ways to express a dot product (it's commutative!):

$$ 
\begin{align*}

\mathbf{v} \cdot \mathbf{w} = \Sigma_{i=1}^n v_i w_i &= \mathbf{v}^\mathrm{T}\mathbf{w} = \Vert\mathbf{v}\Vert\:\Vert\mathbf{w}\Vert \cos \theta \\
& = \mathbf{w}^\mathrm{T}\mathbf{v} = \Vert\mathbf{w}\Vert\:\Vert\mathbf{v} \Vert \cos \theta = \mathbf{w} \cdot \mathbf{v}

\end{align*}
$$


In [7]:
from numpy import arccos, dot

# Compute the dot product of vectors v = [10, 9, 3] and w = [2, 5, 12]
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
u = dot(v, w.T)  # w.T to match inner dims
print("Vector dot product: v • w =", u[0][0])

# Compute the angle between vectors v and w
theta = arccos(u / (norm(v) * norm(w)))  # w.T to match inner dims, norm() default is L2
print("Theta =", theta[0][0])


Vector dot product: v • w = 101
Theta = 0.979924710443726


### 5.2. Vector Hadamard (element-wise) product, $\mathbf{v}\odot \mathbf{w}$:

- Definition: Element-wise product, where the vectors **must be of the same dimension**
    - This method also works for matrices of the same dimension.
    - Output vector/matrix is of the same dimension as the operands.
- Notation: $\mathbf{v}\odot \mathbf{w}$ (sometimes $\mathbf{v}\circ \mathbf{w}$)
    - Elements of the resultant vector are given by: $ (\mathbf{v}\odot \mathbf{w})_{i} = (\mathbf{v})_{i}(\mathbf{w})_{i} $
- Example:

\begin{bmatrix}2&3&1\end{bmatrix} \odot {\begin{bmatrix}3&1&4\end{bmatrix}}={\begin{bmatrix}2\times 3&3\times 1&1\times 4\end{bmatrix}}={\begin{bmatrix}6&3&4\end{bmatrix}}


In [8]:
# Compute the Hadamard product of vectors v = [2, 3, 1] and w = [3, 1, 4]
v = np.array([[2, 3, 1]])
w = np.array([[3, 1, 4]])
u = np.multiply(v, w)

print("Vector Hadamard product:\nv ⊙ w =", u[0])


Vector Hadamard product:
v ⊙ w = [6 3 4]


### 5.3. Vector cross product, $\mathbf{v}\times \mathbf{w}$

Geometric interpretation: The cross product $\mathbf{v} \times \mathbf{w}$ is <mark>a vector perpendicular to both</mark> $\mathbf{v}$ <mark>and</mark> $\mathbf{w}$, <mark>whose length equals the area enclosed by the parallelogram created by the two vectors</mark>

- Cross product definition: 
$$\mathbf{v} \times \mathbf{w} = \Vert \mathbf{v} \Vert \: \Vert \mathbf{w} \Vert\sin{(\theta)} \, \mathbf{n}$$
- Where: 
    - $\theta$ can by computed via dot product
    - $\mathbf{n}$ is a unit vector (i.e. length $1$) perpendicular to both $\mathbf{v}$ and $\mathbf{w}$.

In [9]:
# Compute the cross product of v = [0,2,0] and w = [3,0,0]
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
u = np.cross(v, w)

print("Vector cross product:\nv ⨉ w =", u[0])


Vector cross product:
v ⨉ w = [ 0  0 -6]


## 6. Matrices

These are $\mathbb{R}^{m\times n}$ objects.

### 6.1. <mark>Geometric intuition (from 3B1B)</mark>:
- <mark>Think of matrices as **encoding** linear transformations of vector spaces</mark>
    - I.e. A matrix $\mathbf{A}$ moves **every input vector** (more precisely, the **point where every vector's tip is**) **linearly** to a new location.
- The columns of the matrix can be thought of as **landing points** for the basis (unit) vectors $\hat{i}$ and $\hat{j}$ after the transformation is applied
- A linear transformation means after applying the matrix $\mathbf{A}$:
    - **the origin remains fixed**, and 
    - **all grid lines in the space remain straight, parallel, and evenly spaced**

### 6.2. Length: 

If you treat the $m \times n$ elements of $\mathbf{M}$ as an $mn$-dimensional (flattened 2D to 1D) **"vector"**, the $p$-norm of that "vector" is:

$$\Vert \mathbf{M} \Vert_{p} = \sqrt[p]{(\sum_i^m \sum_j^n |m_{ij}|^p)}$$

For a matrix we also commonly use the L2 norm (referred to as the ***Frobenius norm***) to calculate its magnitude vector. Substitute $p=2$ above

## 7. Matrix addition, $\mathbf{A} + \mathbf{B}$

Same mechanics as for vectors (see above)
* **Matrix addition**: $\mathbf{M} = \mathbf{A} + \mathbf{B}$ is the matrix with elements $M_{ij} = A_{ij} + B_{ij}$


In [10]:
# Sum matrices A and B:
A = np.array([[1, 7], [2, 3], [5, 0]])
B = np.array([[3, 1], [4, 7], [9, 5]])
M = A + B

print("Matrix addition: \nA + B =\n", M)


Matrix addition: 
A + B =
 [[ 4  8]
 [ 6 10]
 [14  5]]


## 8. Scalar-matrix multiplication, $\alpha\mathbf{A}$
* **Scalar multiplication of a matrix**: $\mathbf{M} = \alpha \mathbf{A}$ is the matrix with elements $M_{ij} = \alpha A_{ij}$


In [11]:
# Multiply matrix A by scalar value alpha = 2
A = np.array([[1, 7], [2, 3], [5, 0]])
alpha = 2
M = alpha * A

print("Scalar matrix multiplication: \nalpha * A =\n", M)


Scalar matrix multiplication: 
alpha * A =
 [[ 2 14]
 [ 4  6]
 [10  0]]


## 9. Matrix multiplication (4 approaches)
### 9.1. Matrix times vector multiplication $\mathbf{Av}$ (<mark>important</mark>)

<mark>Geometric intuition (3B1B)</mark>:
- A matrix $\mathbf{A}$ represents a <mark>linear transformation of a vector space</mark> (where $\mathbf{A} \isin \mathbb{R}^{m \times n}$).
- Matrix-vector multiplication $\mathbf{v_{new}=Av}$ <mark>applies this transformation</mark> (encoded in $\mathbf{A}$) <mark>to a column vector</mark> $\mathbf{v}$ (where $\mathbf{v} \isin \mathbb{R}^{n \times 1}$).
    - Note how inner dimensions match: $\mathbf{A} \isin \mathbb{R}^{m \times n}$ and $\mathbf{v} \isin \mathbb{R}^{n \times 1}$, therefore the result $\mathbf{v_{new}}$ will also be a column vector, albeit in $\mathbb{R}^{m \times 1}$.
- Elements of the resultant vector (let's call it $\mathbf{y=v_{new}}$) are given by: $$ y_i = \sum _{j=1}^{n}a_{ij}v_{j} $$
- <mark>**3B1B intuition for square matrices**</mark>: 
    - The new vector $\mathbf{v_{new}}$ will be a linear combination of the columns of $\mathbf{A}$ (i.e. where the basis vectors $\hat{i}$ and $\hat{j}$ **end up** in the new space)
    - with coefficients given by the elements of $\mathbf{v}$.
    - For non-square matrices see [this link](https://math.stackexchange.com/questions/1988948/geometric-interpretation-of-non-square-matrices)


In [12]:
# Multiply matrix A by (column) vector v = [2, 3]
A = np.array([[1, 7], [2, 3], [5, 0]])
v = np.array([[2], [3]])  # column vector
M = A @ v

print("Matrix vector multiplication: \nAv =\n", M)


Matrix vector multiplication: 
Av =
 [[23]
 [13]
 [10]]


### 9.2. Vector times matrix multiplication, $\mathbf{v}^\mathrm{T}\mathbf{A}$
- To multiply a (column) vector by a matrix, first transpose the vector $\mathbf{v}$ (i.e. make it a **row** vector $\mathbf{v}^\mathbf{T}$) to make the inner dimensions match.
    - Note how in $\mathbf{v_{new}=v}^\mathrm{T}\mathbf{A}$, inner dimensions match: $\mathbf{v}^\mathrm{T} \isin \mathbb{R}^{1 \times m}$, and $\mathbf{A} \isin \mathbb{R}^{m \times n}$ therefore the result $\mathbf{v_{new}}$ will also be a row vector in $\mathbb{R}^{1 \times n}$.
- Elements of the resultant vector (let's call it $\mathbf{y=v_{new}}$) are given by: $$y_{k}=\sum _{j=1}^{n}v_{j}a_{jk}$$
  

In [13]:
# Transpose the column vector v = [2, 3, 1], and multiply the resulting row vector v^T by matrix A
v = np.array([[2], [3], [1]])  # column vector
A = np.array([[1, 7], [2, 3], [5, 0]])
M = v.T @ A  # v.T is a row vector

print("Vector matrix multiplication: \nv^T A =", M[0])


Vector matrix multiplication: 
v^T A = [13 23]


### 9.3. Matrix times matrix Hadamard (element-wise) product, $A\odot B$:

- Definition (same as for vectors): Element-wise product on two matrices of same-dimension (i.e. $A, B\isin \mathbb{R}^{m \times n}$)
- Elements of the resultant matrix are given by: $ (A\odot B)_{ij} = (A)_{ij}(B)_{ij} $. Example:

\begin{bmatrix}2&3&1\\0&8&-2\end{bmatrix} \odot {\begin{bmatrix}3&1&4\\7&9&5\end{bmatrix}}={\begin{bmatrix}2\times 3&3\times 1&1\times 4\\0\times 7&8\times 9&-2\times 5\end{bmatrix}}={\begin{bmatrix}6&3&4\\0&72&-10\end{bmatrix}}


In [14]:
# Compute the Hadamard product of matrices A and B:
A = np.array([[2, 3, 1], [0, 8, -2]])
B = np.array([[3, 1, 4], [7, 9, 5]])
M = np.multiply(A, B)

print("Matrix Hadamard product: \nA ⊙ B =\n", M)


Matrix Hadamard product: 
A ⊙ B =
 [[  6   3   4]
 [  0  72 -10]]


### 9.4. Matrix times matrix multiplication, $\mathbf{AB}$ (use `np.dot(A,B)` to multiply)

The inner matrix dimensions of the two matrices (e.g. $\mathbf{A}$ and $\mathbf{B}$) **must match**. 
- $\mathbf{A}$ is of dimension $\mathbb{R}^{m \times p}$
- $\mathbf{B}$ is of dimension $\mathbb{R}^{p \times n}$ 
- Here, the dimension of size $p$ is the **inner matrix dimension**. 
    - If they match, it means # columns in $\mathbf{A}$ equals # rows in $\mathbf{B}$.
- Dimensions $m$ and $n$ are the **outer matrix dimensions**. Thus each element of $\mathbf{M=AB}$ can be computed as:

$$M_{ij} = \sum_{k=1}^p P_{ik}Q_{kj}$$

- <mark>I.e. (important)</mark> the $i,j$'th element of $\mathbf{M}$ is the dot product of the $i$'th row of $\mathbf{A}$ with $j$'th column of $\mathbf{Q}$

In [17]:
# Multiply A=[[1,7],[2,3],[5,0]] and B=[[2,6,3,1],[1,2,3,4]] -> [3x2] * [2x4] = output [3x4]

A = np.array([[1, 7], [2, 3], [5, 0]])
B = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print("A =\n", A)
print("\nB =\n", B)
print("\nAB =\n", np.dot(A, B))  # <-- inner dimensions match (p=2). output is a [3x4] matrix


A =
 [[1 7]
 [2 3]
 [5 0]]

B =
 [[2 6 3 1]
 [1 2 3 4]]

AB =
 [[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


In [18]:
# Multiplying B and A will raise a ValueError
np.dot(B, A)  # <-- inner dimensions don't match ...4] * [3...; Error


ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

## 7. Square matrices

Square matrices have dimension $n \times n$, i.e. $A \isin \mathbb{R}^{n \times n}$

### 7.1. Determinant, $\text{det}(\textbf{M})$
- The **Determinant**, $det(\textbf{M})$, is an important property of square matrices.
- <mark>**Geometric intuition of a determinant**</mark> (From 3B1B):
    - Its absolute value tells you how much an area increases/decreases after the transformation by matrix $\textbf{M}$
    - A **negative sign** tells you whether the vector space was "flipped" (i.e. if the basis vectors swapped sides)
    - <mark>**If the determinant is 0**</mark>, it means space has dropped **into fewer dimensions**
        - i.e. **at least 1 dimension is LOST*, so initial the area, volume, etc of the vector space is now 0
        - e.g. if a 2D matrix $\textbf{M}$ transforms areas into a 1D line (or a point), areas get squished to 0; hence $\text{det}(\textbf{M})=0$
- To prove understanding, explain: $\text{det}(\textbf{M}_1 \textbf{M}_2) = \text{det}(\textbf{M}_1) \text{det}(\textbf{M}_2)$

#### Formulae for calculating the determinant of a matrix $\textbf{M}$:

- For a $2 \times 2$ matrix; $det(\textbf{M})$ is:

$$
\begin{split}
|\textbf{M}| = \begin{bmatrix}
a & b \\
c & d\\
\end{bmatrix} = ad - bc\end{split}
$$


- For a $3 \times 3$ matrix; $det(\textbf{M})$ is:

$$
\begin{split}
% \begin{eqnarray*}
\begin{align*}
|\textbf{M}| = \begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{bmatrix} & = a\begin{bmatrix}
\Box &\Box  &\Box  \\
\Box & e & f \\
\Box & h & i \\
\end{bmatrix} - b\begin{bmatrix}
\Box &\Box  &\Box  \\
d & \Box & f \\
g & \Box & i \\
\end{bmatrix} + c\begin{bmatrix}
\Box &\Box  &\Box  \\
d & e & \Box \\
g & h & \Box \\
\end{bmatrix} \\
&&\\
& = a\begin{bmatrix}
e & f \\
h & i \\
\end{bmatrix} - b\begin{bmatrix}
d & f \\
g & i \\
\end{bmatrix} + c\begin{bmatrix}
d & e \\
g & h \\
\end{bmatrix} \\ 
&&\\
& = aei + bfg + cdh - ceg - bdi - afh
% \end{eqnarray*}
\end{align*}
\end{split}
$$

- For higher dimension matrices, a similar approach can be used.

### 7.2. Identity matrix

- A square matrix, $\textbf{I}$, with **ones on the diagonal** and **zeros everywhere else**
- Multiplying a matrix with $\textbf{I}$ (of compatible dimensionality) will produce the same matrix (like how $n \times 1 = n$)

In [16]:
# Find the determinant of M, and multiply M by np.eye(4) to show M x I = M

from numpy.linalg import det

M = np.array([[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]])
print("M:\n", M)

print(f"Determinant: {det(M):.1f}")
I = np.eye(4)
print("\nI:\n", I)
print("\nM*I:\n", np.dot(M, I))


M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0

I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


## 8. Matrix inverse

For square matrices ($\mathbb{R}^{n\times n}$), $\textbf{M}^{-1}$ is the inverse of $\textbf{M}$ if $\textbf{M} \cdot \textbf{M}^{-1} = I$ (like how $3 \times \frac{1}{3} = 1$)

- A matrix is **invertible** if it has an inverse (non-square matrices are **not** invertible)
- The inverse of a matrix is unique: An invertible matrix **only has one inverse**.
- For a $2 \times 2$ matrix, the inverse is:
$$
\begin{split}
\textbf{M}^{-1} = \begin{bmatrix}
a & b \\
c & d\\
\end{bmatrix}^{-1} = \frac{1}{|\textbf{M}|}\begin{bmatrix}
d & -b \\
-c & a\\
\end{bmatrix}\end{split}
$$


### 8.1. Is it invertible?

- **Singular matrices** are those which have **no inverses** (like how 0 has no inverse)
    - $det(\textbf{M}) = 0$
- **Nonsingular matrices** are those which **do have an inverse**
    - $det(\textbf{M}) \ne 0$

In [ ]:
# Recall, M has non-zero determinant so is invertible; but det(P)=0 so it can't be inverted

from numpy.linalg import inv

print(f"Determinant: {det(M):.1f}")
print("Inv M:\n", inv(M))

P = np.array([[0, 1, 0], [0, 0, 0], [1, 0, 1]])
print("det(p):", det(P))
print("Inv P:\n", inv(P))  # <-- Error thrown because P is Singular (non-invertible)


### 8.2. Ill-Conditioned Matrices

- An ill-conditioned matrix is one which is **close to being singular** 
    - Its determinant will be close to 0 (problematic in the same way dividing by a tiny number is)
    - Computation errors (overflow, underflow, round-off errors) may occur
- **Condition number**: ***Higher number*** means the matrix is ***more*** ill-conditioned (i.e. closer to being singular)

### 8.3. Trace 

- The **trace** of $\textbf{A} : \textbf{A} \in \mathbb{R}^{n\times n}$ is the sum of elements on the main diagonal (from left to right):

$$ \text{tr}(\textbf{A}) = \sum_{i=1}^{n} a_{ii} $$


## 9. Back to non-square matrices

### 9.1. Rank

- The **rank** of $\textbf{A} : \textbf{A} \in \mathbb{R}^{m\times n}$ is the **number of linearly independent columns or rows** in $\textbf{A}$
    - NB: Num. of lin. indep. cols. in a matrix $\equiv$ Num. of lin. indep. rows in that matrix

#### 9.1.1. "Full Rank" Matrix

- $\textbf{A}$ is **full rank** if $\text{rank}(\textbf{A}) = \min(m,n)$
- $\textbf{A}$ is also full rank if **all its columns are linearly independent**

#### 9.1.2. Augmented Matrix

- If vector $\textbf{y}$ is concatenated to matrix $\textbf{A}$, we say "$\textbf{A}$ augmented with $\textbf{y}$".
    - if $\text{rank}([\textbf{A},\textbf{y}]) = \text{rank}(\textbf{A})+1$, then vector $\textbf{y}$ is **"new" information**
    - otherwise it means $\textbf{y}$ can be created as a linear combination of the columns in $\textbf{A}$



In [ ]:
# Compute the condition number and rank for matrix A = [[1,1,0],[0,1,0],[1,0,1]]
# If y = [[1],[2],[1]], get the augmented matrix [A,y]

from numpy import trace
from numpy.linalg import cond, matrix_rank

A = np.array([[1, 1, 0], [0, 1, 0], [1, 0, 1]])

print("Condition number:", cond(A))
print("Rank:", matrix_rank(A))
print("Trace:", trace(A))
y = np.array([[1], [2], [1]])
print("A matrix's shape:", A.shape, "\ny vector's shape", y.shape)
A_y = np.concatenate((A, y), axis=1)
print("Augmented matrix:\n", A_y)


# 10. 3Blue1Brown's aside
## A few useful transformations

### Vector Transformations

### Matrix Transformations (TBC double check)

$$ \begin{align*} 
\text{No change (Identity matrix)} &: \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Translation} &: \text{NA} &\text{in 3D:} \begin{bmatrix} 1 & 0 & X \\ 0 & 1 & Y \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Scaling (about origin)} &: \begin{bmatrix} W & 0 \\ 0 & H \end{bmatrix} &\text{in 3D:} \begin{bmatrix} W & 0 & 0 \\ 0 & H & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Rotation (about origin)} &: \begin{bmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{bmatrix} &\text{in 3D:} \begin{bmatrix} \cos\theta & -\sin\theta & 0 \\ \sin\theta & \cos\theta & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Shear (in x-direction)} &: \begin{bmatrix} 1 & \tan\phi \\ 0 & 1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} 1 & \tan\phi & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Shear (in y-direction)} &: \begin{bmatrix} 1 & 0 \\ \tan\psi & 1 \end{bmatrix} &\text{in 3D:}\begin{bmatrix} 1 & 0 & 0 \\ \tan\psi & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Reflect (about origin)} &: \begin{bmatrix} -1 & 0 \\ 0 & -1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} -1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Reflect (about x-axis)} &: \begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} 1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Reflect (about y-axis)} &: \begin{bmatrix} -1 & 0 \\ 0 & 1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} -1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\end{align*} $$