# Linear Algebra - Vectors

## 1. Vectors

### Notation:
- A vector, $\textbf{v}$, is a list of numbers (scalars) arranged in a particular order.
- By convention, vectors are implicitly **column vectors**. So $\textbf{v} \in \mathbb{R}^{n}$; or implicitly $\textbf{v} \in \mathbb{R}^{n \times 1}$.
- To represent a column vector, $\textbf{v}$, as a **row vector**, take its **transpose** $\textbf{v}^\mathrm{T}$. Hence, $\textbf{v}^\mathrm{T} \in \mathbb{R}^{1 \times n}$.
    - **Transpose** operation turns a column vector into a row vector vice versa. For matrices, it swaps rows and columns.
- The $i$'th element of vector $\mathbf{v}$ is denoted $v_i$.

### Properties and geometric interpretation of a vector:
- The number of elements in a vector is called its **dimension**. This also tells us the vector space it belongs to.
    - For example, $\mathbf{v} \in \mathbb{R}^{3}$ is an 3-dimensional vector.
- A vector can be thought of as an arrow in n-dimensional space.
- The **magnitude** of a vector is its **length** in n-dimensional space. (many distance formulas can be used to compute):
    - $L_2$ norm (Euclidian length): $\Vert\mathbf{v}\Vert_2 = \sqrt{\Sigma_i w_{i}^{2}}\quad$ (*physical length* of a vector in n-dim space)
    - $L_1$ norm (Manhattan Distance): $\Vert\mathbf{v}\Vert_1 = \Sigma_i |v_i|\quad $
    - More generally, 
        - The **p-norm** is $\Vert v \Vert_{p} = \sqrt[p]{(\sum_i v_i^p)}$
        - And the $L_\infty$ norm, $\Vert\mathbf{v}\Vert_\infty$, is the $p$-norm where $p=\infty$
    - Generally the $L_2$ norm is implied when referring to vector length. 
      - Hence $\Vert\mathbf{v}\Vert_2$ can be written more simply as $\Vert\mathbf{v}\Vert$ or occasionally $|\mathbf{v}|$ (though the latter is ambiguous with the absolute value of a scalar)

In [1]:
import numpy as np

# Create a row vector and a column vector, show their shapes
row_vec = np.array([[1, -5, 3, 2, 4]])
col_vec = np.array([[1], [2], [3], [4]])

# Comments show output if you don't use list of lists
print("row_vec =", row_vec[0], "\nrow_vec shape:", row_vec.shape)  # [ 1 -5  3  2  4] and (1, 5)
print("\ncol_vec =\n", col_vec, "\ncol_vec shape:", col_vec.shape)  # [1 2 3 4] and (4, 1)


row_vec = [ 1 -5  3  2  4] 
row_vec shape: (1, 5)

col_vec =
 [[1]
 [2]
 [3]
 [4]] 
col_vec shape: (4, 1)


In [2]:
# Transpose row_vec and calculate L1, L2, and L_inf norms
from numpy.linalg import norm

print("row_vec =", row_vec[0], "\nrow_vec shape:", row_vec.shape)

transposed_row_vec = row_vec.T  # now a column vector
print("\ntransposed_row_vec =", transposed_row_vec, "\ntransposed_row_vec shape:", transposed_row_vec.shape, "\n")

norm_1 = norm(transposed_row_vec, 1)
norm_2 = norm(transposed_row_vec, 2)  # <- L2 norm is default and most common
norm_inf = norm(transposed_row_vec, np.inf)

print("Measures of magnitude:")
print(f"L_1 norm is: {norm_1:.1f}")
print(f"L_2 norm is: {norm_2:.1f}", "(most common)")
print(f"L_inf norm is: {norm_inf:.1f}", "(absolute value of largest element)")  # NB: norm_inf = |largest element|


row_vec = [ 1 -5  3  2  4] 
row_vec shape: (1, 5)

transposed_row_vec = [[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]] 
transposed_row_vec shape: (5, 1) 

Measures of magnitude:
L_1 norm is: 15.0
L_2 norm is: 7.4 (most common)
L_inf norm is: 5.0 (absolute value of largest element)


## 2. Vector addition, $\mathbf{v} + \mathbf{w}$

Elementwise addition; if vectors are of of same length (i.e. if $\mathbf{v}$ and $\mathbf{w}$ are both in $\mathbb{R}^n$) then:

- **Addition of 2 vectors**: $\mathbf{u} = \mathbf{v} + \mathbf{w}$ is the vector with elements $u_i = v_i + w_i$


In [3]:
# Sum vectors v = [10, 9, 3] and w = [2, 5, 12]
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
u = v + w

print("Vector addition: \nv + w =", u[0])


Vector addition: 
v + w = [12 14 15]


## 3. Scalar times vector, $\alpha\mathbf{v}$

To multiply a vector $\mathbf{v}$, by a scalar $\alpha$ (a number in $\mathbb{R}$), do it "elementwise" or "pairwise".

- **Scalar multiplication of a vector**: $\mathbf{u} = \alpha \mathbf{v}$ is the vector with elements $u_i = \alpha v_i$

In [4]:
# Multiply vector v = [10, 9, 3] by scalar alpha = 4
v = np.array([[10, 9, 3]])
alpha = 4
u = alpha * v

print("Scalar times vector: \nalpha * v =", u[0])


Scalar times vector: 
alpha * v = [40 36 12]


### 3.1. Linear Combinations

- A **linear combination** of set $S$ is defined as $\Sigma \alpha_i s_i$
    - Here $\alpha_i$ values are the **coefficients** of $s_i$ values
    - Example: Grocery bill total cost is a linear combination of items purchased:
        - $\displaystyle{\sum c_i n_i}$ ($c_i$ is item cost, $n_i$ is qty. purchased)
    
### 3.2. Linear Dependence and Independence
    
- A set is **linearly INdependent** if no object in the set can be written as a lin. combination of the other objects in the set.
    - Example: $\mathbf{v} = [1, 1, 0], \mathbf{w} = [1, 0, 0]$ and $\mathbf{u} = [0, 0, 1]$ are <mark>linearly independent. Can you see why?</mark>
- Below is an example of a **linearly DEpendent** set. $\mathbf{x}$ is dependent on 

In [5]:
# Writing the vector x = [-8, -1, 4] as a linear combination of 3 vectors, v, w, and u:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])

x = 3 * v - 2 * w + 4 * u
print("x is a linear combination of v, w, and u. It is linearly dependent on them: \nx =", x[0])


x is a linear combination of v, w, and u. It is linearly dependent on them: 
x = [-8 -1  4]


## 4. Vector multiplication (4 approaches)

### 4.1. Vector dot (inner) product, $\mathbf{v} \cdot \mathbf{w}$

Geometric interpretation: <mark>A measure of how similarly directed two vectors are</mark>

- Definition: $\mathbf{v} \cdot \mathbf{w} = \Sigma_{i=1}^n v_i w_i$
    - It's the sum of elementwise products. For $\mathbf{v}, \mathbf{w} \in \mathbb{R}^n$, 
- Note also, since $\mathbf{v}, \mathbf{w} \in \mathbb{R}^n$, transpose to make inner dimensions match. Dot product can hence be rewritten as:
    - $\mathbf{v} \cdot \mathbf{w} = \mathbf{v}^\mathrm{T}\mathbf{w}$

#### Angle between vectors, $\theta$

- Think of dot product as "**degree of alignment**": $\mathbf{v} \cdot \mathbf{w} = \Vert\mathbf{v}\Vert\:\Vert\mathbf{w}\Vert \cos \theta$
    - (1,1) and (2,2) are **parallel**; computing the angle gives $\theta = 0$
    - (1,1) and (-1,1) are **orthogonal** (perpendicular) bc $\theta = \pi/2$ and $\mathbf{v} \cdot \mathbf{w} = 0$ (no alignment)

* Extending on the dot product idea, $\mathbf{v} \cdot \mathbf{w}$, the **angle between two vectors** is $\theta$. It is as defined by the formula:
$$ \theta = \arccos \left({\frac {\mathbf{v} \cdot \mathbf{w}}{\left\|\mathbf{v}\right\|\left\|\mathbf{w} \right\|}}\right) $$

#### Recap: Many ways to express a dot product (it's commutative!):

$$ 
\begin{align*}

\mathbf{v} \cdot \mathbf{w} = \Sigma_{i=1}^n v_i w_i &= \mathbf{v}^\mathrm{T}\mathbf{w} = \Vert\mathbf{v}\Vert\:\Vert\mathbf{w}\Vert \cos \theta \\
& = \mathbf{w}^\mathrm{T}\mathbf{v} = \Vert\mathbf{w}\Vert\:\Vert\mathbf{v} \Vert \cos \theta = \mathbf{w} \cdot \mathbf{v}

\end{align*}
$$


In [6]:
from numpy import arccos, dot

# Compute the dot (i.e. inner) product of vectors v = [10, 9, 3] and w = [2, 5, 12]
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
u = dot(v, w.T)  # w.T to match inner dims, manually need to transpose w to column vector
u1 = np.inner(v, w)  # same as dot, but more explicit. Can be used for higher dims. Assumes all inputs column vectors

print("Vector dot product: v • w =", u[0][0])
print("Alternative calculation:", u1[0][0])

# Compute the angle between vectors v and w
theta = arccos(u / (norm(v) * norm(w)))  # w.T to match inner dims, norm() default is L2
print("\nTheta =", theta[0][0])


Vector dot product: v • w = 101
Alternative calculation: 101

Theta = 0.979924710443726


### 4.2. Vector outer product, $\mathbf{v} \otimes \mathbf{w}$

- Definition: $\mathbf{v} \otimes \mathbf{w}$ is the $m \times n$ matrix $\textbf{A}$ obtained by multiplying each element of $\mathbf{v}$ by each element of $\mathbf{w}$.
    - Unlike with the dot product, here the vectors $\textbf{v}$ and $\textbf{w}$ may have different lengths: $\mathbf{v} \in \mathbb{R}^{m\times 1}$, $ \mathbf{w} \in \mathbb{R}^{n\times 1}$.
    - Elements of the resultant matrix are given by: $ (\mathbf{v} \otimes \mathbf{w} )_{ij}=v_{i}w_{j} $
    - The entire matrix is represented as: $$ \mathbf {v} \otimes \mathbf {w} =\mathbf {A} ={\begin{bmatrix}v_{1}w_{1}&v_{1}w_{2}&\dots &v_{1}w_{n}\\v_{2}w_{1}&v_{2}w_{2}&\dots &v_{2}w_{n}\\\vdots &\vdots &\ddots &\vdots \\v_{m}w_{1}&v_{m}w_{2}&\dots &v_{m}w_{n}\end{bmatrix}} $$

- Note also, since $\mathbf{v}$ and $\mathbf{w}$ are column vectors ($\mathbf{v} \in \mathbb{R}^{m\times 1}$, $ \mathbf{w} \in \mathbb{R}^{n\times 1}$), we can transpose $\textbf{w}^\textrm{T}$ (now a row vector, $ \mathbf{w}^\mathrm{T} \in \mathbb{R}^{1\times n}$). 
    - $\mathbf{v} \otimes \mathbf{w}$ is hence equivalent to the matrix multiplication $\textbf{v}\textbf{w}^\textrm{T}$ (since this ensures the inner dimensions ($1$) to match). Example: $$ \mathbf {v} \otimes \mathbf {w} =\mathbf {v} \mathbf {w} ^{\textsf {T}}={\begin{bmatrix}v_{1}\\v_{2}\\v_{3}\\v_{4}\end{bmatrix}}{\begin{bmatrix}w_{1}&w_{2}&w_{3}\end{bmatrix}}={\begin{bmatrix}v_{1}w_{1}&v_{1}w_{2}&v_{1}w_{3}\\v_{2}w_{1}&v_{2}w_{2}&v_{2}w_{3}\\v_{3}w_{1}&v_{3}w_{2}&v_{3}w_{3}\\v_{4}w_{1}&v_{4}w_{2}&v_{4}w_{3}\end{bmatrix}} $$

In [7]:
# Compute the outer product of same vectors v = [10, 9, 3] and w = [2, 5, 12]
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
# w = np.array([[2, 5, 12, 13]])  # <- uncomment to see outer product with different dimensions

outer = np.outer(v, w)  # Assumes all inputs column vectors
outer2 = np.outer(w, v)  # Assumes all inputs column vectors
inner = np.inner(v, w)  # As previous cell

print("Vectors:\nv =", v[0], "\nw =", w[0])
print("\nVector inner product: v • w =", inner[0][0])
print("\nVector outer product: v ⨂ w =\n", outer)
print("\nVector outer product flipped: w ⨂ v =\n", outer2)


Vectors:
v = [10  9  3] 
w = [ 2  5 12]

Vector inner product: v • w = 101

Vector outer product: v ⨂ w =
 [[ 20  50 120]
 [ 18  45 108]
 [  6  15  36]]

Vector outer product flipped: w ⨂ v =
 [[ 20  18   6]
 [ 50  45  15]
 [120 108  36]]


### 4.3. Vector Hadamard (element-wise) product, $\mathbf{v}\odot \mathbf{w}$:

- Definition: Element-wise product, where the vectors **must be of the same dimension**
    - This method also works for matrices of the same dimension.
    - Output vector/matrix is of the same dimension as the operands.
- Notation: $\mathbf{v}\odot \mathbf{w}$ (sometimes $\mathbf{v}\circ \mathbf{w}$)
    - Elements of the resultant vector are given by: $ (\mathbf{v}\odot \mathbf{w})_{i} = (\mathbf{v})_{i}(\mathbf{w})_{i} $
- Example:

$$ \begin{bmatrix}2&3&1\end{bmatrix} \odot {\begin{bmatrix}3&1&4\end{bmatrix}}={\begin{bmatrix}2\times 3&3\times 1&1\times 4\end{bmatrix}}={\begin{bmatrix}6&3&4\end{bmatrix}} $$

In [8]:
# Compute the Hadamard product of vectors v = [2, 3, 1] and w = [3, 1, 4]
v = np.array([[2, 3, 1]])
w = np.array([[3, 1, 4]])
u = np.multiply(v, w)

print("Vector Hadamard product:\nv ⊙ w =", u[0])


Vector Hadamard product:
v ⊙ w = [6 3 4]


### 4.4. Vector cross product, $\mathbf{v}\times \mathbf{w}$

Geometric interpretation: The cross product $\mathbf{v} \times \mathbf{w}$ is <mark>a vector perpendicular to both</mark> $\mathbf{v}$ <mark>and</mark> $\mathbf{w}$, <mark>whose length equals the area enclosed by the parallelogram created by the two vectors</mark>

- Cross product definition: 
$$\mathbf{v} \times \mathbf{w} = \Vert \mathbf{v} \Vert \: \Vert \mathbf{w} \Vert\sin{(\theta)} \, \mathbf{n}$$
- Where: 
    - $\theta$ can by computed via dot product
    - $\mathbf{n}$ is a unit vector (i.e. length $1$) perpendicular to both $\mathbf{v}$ and $\mathbf{w}$.

In [9]:
# Compute the cross product of v = [0,2,0] and w = [3,0,0]
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
u = np.cross(v, w)

print("Vector cross product:\nv ⨉ w =", u[0])


Vector cross product:
v ⨉ w = [ 0  0 -6]
