# Linear Algebra - Vectors

## 0. Key Takeaways:

### 0.1. Syntax 

- To define vectors and matrices in NumPy, use `np.array([[]])` with double square brackets
    - A row vector: `[[ csv row elements ]]`
    - A column vector: `[[elem 1], [elem 2], elem 3]]`, and you can put each on a new line
    - A matrix: ``[[ csv row 1], [ csv row 2], ...]``, and you can put each on a new line

### 0.2. Concepts covered
- Basics set notation (previous notebook)
- Vectors 
    - Definition and properties (transpose, length `norm`s)
    - Addition
    - Multiplication (scalar, dot, and cross product)
    - Angle between 2 vectors (via dot product)

## 1. Vectors

### Properties of a vector $\mathbf{v}$:
- $i$'th element: $v_i$
- Transpose (turns columns into rows and vice versa): $\mathbf{v}^\mathrm{T}$ (for a matrix it swaps rows with columns)
    - By convention, vectors are implicitly column vectors. Hence, to represent $\mathbf{v}$ as a row vector, we denote its transposed form: $\mathbf{v}^\mathrm{T}$.
- Length (many definitions (distance formulas) we can use):
    - $L_2$ norm (Euclidian length): $\Vert\mathbf{v}\Vert_2 = \sqrt{\Sigma_i v_{i}^{2}}\quad$ (*physical length* of a vector in n-dim space)
    - $L_1$ norm (Manhattan Distance): $\Vert\mathbf{v}\Vert_1 = \Sigma_i |v_i|\quad $
    - More generally, 
        - The **p-norm** is $\Vert v \Vert_{p} = \sqrt[p]{(\sum_i v_i^p)}$
        - And the $L_\infty$ norm, $\Vert\mathbf{v}\Vert_\infty$, is the $p$-norm where $p=\infty$
- Generally the $L_2$ norm is implied when referring to vector length. 
  - Hence $\Vert\mathbf{v}\Vert_2$ can be written more simply as $\Vert\mathbf{v}\Vert$ or occasionally $|\mathbf{v}|$ (though the latter is ambiguous with the absolute value of a scalar)

In [1]:
import numpy as np

# Create a row vector and a column vector, show their shapes
row_vec = np.array([[1, -5, 3, 2, 4]])
col_vec = np.array([[1], [2], [3], [4]])

# Comments show output if you don't use list of lists
print(row_vec[0])  # [ 1 -5  3  2  4]
print(col_vec)  # [1 2 3 4]
print(row_vec.shape)  # (5,)
print(col_vec.shape)  # (4,)


[ 1 -5  3  2  4]
[[1]
 [2]
 [3]
 [4]]
(1, 5)
(4, 1)


In [2]:
# Transpose row_vec and calculate L1, L2, and L_inf norms
from numpy.linalg import norm

transposed_row_vec = row_vec.T  # now a column vector
print(transposed_row_vec)

norm_1 = norm(transposed_row_vec, 1)
norm_2 = norm(transposed_row_vec, 2)  # <- L2 norm is default and most common
norm_inf = norm(transposed_row_vec, np.inf)

print(f"L_1 is: {norm_1:.1f}")
print(f"L_2 is: {norm_2:.1f}")
print(f"L_inf is: {norm_inf:.1f}")  # NB: norm_inf = |largest element|


[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


## 2. Vector addition, $\mathbf{v} + \mathbf{w}$

Elementwise addition; if vectors are of of same length (i.e. if $\mathbf{v}$ and $\mathbf{w}$ are both in $\mathbb{R}^n$) then:

- **Addition of 2 vectors**: $\mathbf{u} = \mathbf{v} + \mathbf{w}$ is the vector with elements $u_i = v_i + w_i$


In [3]:
# Sum vectors v = [10, 9, 3] and w = [2, 5, 12]
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
u = v + w

print("Vector addition: \nv + w =", u[0])


Vector addition: 
v + w = [12 14 15]


## 3. Scalar-vector multiplication, $\alpha\mathbf{v}$

To multiply a vector $\mathbf{v}$, by a scalar $\alpha$ (a number in $\mathbb{R}$), do it "elementwise" or "pairwise".

- **Scalar multiplication of a vector**: $\mathbf{u} = \alpha \mathbf{v}$ is the vector with elements $u_i = \alpha v_i$

In [4]:
# Multiply vector v = [10, 9, 3] by scalar alpha = 4
v = np.array([[10, 9, 3]])
alpha = 4
u = alpha * v

print("Scalar vector multiplication: \nalpha * v =", u[0])


Scalar vector multiplication: 
alpha * v = [40 36 12]


### 3.1. Linear Combinations

- A **linear combination** of set $S$ is defined as $\Sigma \alpha_i s_i$
    - Here $\alpha_i$ values are the **coefficients** of $s_i$ values
    - Example: Grocery bill total cost is a linear combination of items purchased:
        - $\displaystyle{\sum c_i n_i}$ ($c_i$ is item cost, $n_i$ is qty. purchased)
    
### 3.2. Linear Dependence and Independence
    
- A set is **linearly INdependent** if no object in the set can be written as a lin. combination of the other objects in the set.
    - Example: $\mathbf{v} = [1, 1, 0], \mathbf{w} = [1, 0, 0]$ and $\mathbf{u} = [0, 0, 1]$ are <mark>linearly independent. Can you see why?</mark>
- Below is an example of a **linearly DEpendent** set. $\mathbf{x}$ is dependent on 

In [5]:
# Writing the vector x = [-8, -1, 4] as a linear combination of 3 vectors, v, w, and u:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])

x = 3 * v - 2 * w + 4 * u
print("x is a linear combination of v, w, and u. It is linearly dependent on them: \nx =", x[0])


x is a linear combination of v, w, and u. It is linearly dependent on them: 
x = [-8 -1  4]


## 4. Vector-vector multiplication (3 approaches)

### 4.1. Vector dot product, $\mathbf{v} \cdot \mathbf{w}$ (i.e. commonly "vector times vector")

Geometric interpretation: <mark>A measure of how similarly directed two vectors are</mark>

- Definition: $\mathbf{v} \cdot \mathbf{w} = \Sigma_{i=1}^n v_i w_i$
    - It's the sum of elementwise products. For $\mathbf{v}, \mathbf{w} \in \mathbb{R}^n$, 
- Note also, since $\mathbf{v}, \mathbf{w} \in \mathbb{R}^n$, transpose to make inner dimensions match. Dot product can hence be rewritten as:
    - $\mathbf{v} \cdot \mathbf{w} = \mathbf{v}^\mathrm{T}\mathbf{w}$

#### Angle between vectors, $\theta$

- Think of dot product as "**degree of alignment**": $\mathbf{v} \cdot \mathbf{w} = \Vert\mathbf{v}\Vert\:\Vert\mathbf{w}\Vert \cos \theta$
    - (1,1) and (2,2) are **parallel**; computing the angle gives $\theta = 0$
    - (1,1) and (-1,1) are **orthogonal** (perpendicular) bc $\theta = \pi/2$ and $\mathbf{v} \cdot \mathbf{w} = 0$ (no alignment)

* Extending on the dot product idea, $\mathbf{v} \cdot \mathbf{w}$, the **angle between two vectors** is $\theta$. It is as defined by the formula:
$$ \theta = \arccos \left({\frac {\mathbf{v} \cdot \mathbf{w}}{\left\|\mathbf{v}\right\|\left\|\mathbf{w} \right\|}}\right) $$

#### Recap: Many ways to express a dot product (it's commutative!):

$$ 
\begin{align*}

\mathbf{v} \cdot \mathbf{w} = \Sigma_{i=1}^n v_i w_i &= \mathbf{v}^\mathrm{T}\mathbf{w} = \Vert\mathbf{v}\Vert\:\Vert\mathbf{w}\Vert \cos \theta \\
& = \mathbf{w}^\mathrm{T}\mathbf{v} = \Vert\mathbf{w}\Vert\:\Vert\mathbf{v} \Vert \cos \theta = \mathbf{w} \cdot \mathbf{v}

\end{align*}
$$


In [6]:
from numpy import arccos, dot

# Compute the dot product of vectors v = [10, 9, 3] and w = [2, 5, 12]
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
u = dot(v, w.T)  # w.T to match inner dims
print("Vector dot product: v • w =", u[0][0])

# Compute the angle between vectors v and w
theta = arccos(u / (norm(v) * norm(w)))  # w.T to match inner dims, norm() default is L2
print("Theta =", theta[0][0])


Vector dot product: v • w = 101
Theta = 0.979924710443726


### 4.2. Vector Hadamard (element-wise) product, $\mathbf{v}\odot \mathbf{w}$:

- Definition: Element-wise product, where the vectors **must be of the same dimension**
    - This method also works for matrices of the same dimension.
    - Output vector/matrix is of the same dimension as the operands.
- Notation: $\mathbf{v}\odot \mathbf{w}$ (sometimes $\mathbf{v}\circ \mathbf{w}$)
    - Elements of the resultant vector are given by: $ (\mathbf{v}\odot \mathbf{w})_{i} = (\mathbf{v})_{i}(\mathbf{w})_{i} $
- Example:

\begin{bmatrix}2&3&1\end{bmatrix} \odot {\begin{bmatrix}3&1&4\end{bmatrix}}={\begin{bmatrix}2\times 3&3\times 1&1\times 4\end{bmatrix}}={\begin{bmatrix}6&3&4\end{bmatrix}}


In [7]:
# Compute the Hadamard product of vectors v = [2, 3, 1] and w = [3, 1, 4]
v = np.array([[2, 3, 1]])
w = np.array([[3, 1, 4]])
u = np.multiply(v, w)

print("Vector Hadamard product:\nv ⊙ w =", u[0])


Vector Hadamard product:
v ⊙ w = [6 3 4]


### 4.3. Vector cross product, $\mathbf{v}\times \mathbf{w}$

Geometric interpretation: The cross product $\mathbf{v} \times \mathbf{w}$ is <mark>a vector perpendicular to both</mark> $\mathbf{v}$ <mark>and</mark> $\mathbf{w}$, <mark>whose length equals the area enclosed by the parallelogram created by the two vectors</mark>

- Cross product definition: 
$$\mathbf{v} \times \mathbf{w} = \Vert \mathbf{v} \Vert \: \Vert \mathbf{w} \Vert\sin{(\theta)} \, \mathbf{n}$$
- Where: 
    - $\theta$ can by computed via dot product
    - $\mathbf{n}$ is a unit vector (i.e. length $1$) perpendicular to both $\mathbf{v}$ and $\mathbf{w}$.

In [8]:
# Compute the cross product of v = [0,2,0] and w = [3,0,0]
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
u = np.cross(v, w)

print("Vector cross product:\nv ⨉ w =", u[0])


Vector cross product:
v ⨉ w = [ 0  0 -6]


In [9]:
# Compute the Hadamard product of matrices A and B:
A = np.array([[2, 3, 1], [0, 8, -2]])
B = np.array([[3, 1, 4], [7, 9, 5]])
M = np.multiply(A, B)

print("Matrix Hadamard product: \nA ⊙ B =\n", M)


Matrix Hadamard product: 
A ⊙ B =
 [[  6   3   4]
 [  0  72 -10]]
