# Linear Algebra - Matrices (Pt 1)


## 0. Key Takeaways:

### 0.1. Syntax 

- To define vectors and matrices in NumPy, use `np.array([[]])` with double square brackets
    - A row vector: `[[ csv row elements ]]`
    - A column vector: `[[elem 1], [elem 2], elem 3]]`, and you can put each on a new line
    - A matrix: ``[[ csv row 1], [ csv row 2], ...]``, and you can put each on a new line

### 0.2. Concepts covered
- Matrices
    - <mark>A matrix is simply an object which transforms space linearly</mark>
    - Definition and properties (transpose, length `norm`s)
    - Addition and scalar multiplication
    - Matrix multiplication (using `np.dot`) - inner dimensions must match
        - *NB: A vector is just a matrix with 1 column (or row if it's a row vector)*

## 1. Matrices

These are $\mathbb{R}^{m\times n}$ objects.

### 1.1. <mark>Geometric intuition (from 3B1B)</mark>:
- <mark>Think of matrices as **encoding** linear transformations of vector spaces</mark>
    - I.e. A matrix $\mathbf{A}$ moves **every input vector** (more precisely, the **point where every vector's tip is**) **linearly** to a new location.
- The columns of the matrix can be thought of as **landing points** for the basis (unit) vectors $\hat{i}$ and $\hat{j}$ after the transformation is applied
- A linear transformation means after applying the matrix $\mathbf{A}$:
    - **the origin remains fixed**, and 
    - **all grid lines in the space remain straight, parallel, and evenly spaced**

### 1.2. Length: 

If you treat the $m \times n$ elements of $\mathbf{M}$ as an $mn$-dimensional (flattened 2D to 1D) **"vector"**, the $p$-norm of that "vector" is:

$$\Vert \mathbf{M} \Vert_{p} = \sqrt[p]{(\sum_i^m \sum_j^n |m_{ij}|^p)}$$

For a matrix we also commonly use the L2 norm (referred to as the ***Frobenius norm***) to calculate its magnitude vector. Substitute $p=2$ above


## 2. Matrix addition, $\mathbf{A} + \mathbf{B}$

Same mechanics as for vectors (see above)
* **Matrix addition**: $\mathbf{M} = \mathbf{A} + \mathbf{B}$ is the matrix with elements $M_{ij} = A_{ij} + B_{ij}$


In [1]:
import numpy as np

# Sum matrices A and B:
A = np.array([[1, 7], [2, 3], [5, 0]])
B = np.array([[3, 1], [4, 7], [9, 5]])
M = A + B

print("Matrix addition: \nA + B =\n", M)


Matrix addition: 
A + B =
 [[ 4  8]
 [ 6 10]
 [14  5]]


## 3. Scalar-matrix multiplication, $\alpha\mathbf{A}$
* **Scalar multiplication of a matrix**: $\mathbf{M} = \alpha \mathbf{A}$ is the matrix with elements $M_{ij} = \alpha A_{ij}$


In [2]:
# Multiply matrix A by scalar value alpha = 2
A = np.array([[1, 7], [2, 3], [5, 0]])
alpha = 2
M = alpha * A

print("Scalar matrix multiplication: \nalpha * A =\n", M)


Scalar matrix multiplication: 
alpha * A =
 [[ 2 14]
 [ 4  6]
 [10  0]]


## 4. Matrix multiplication (4 approaches)
### 4.1. Matrix times vector multiplication $\mathbf{Av}$ (<mark>important</mark>)

<mark>Geometric intuition (3B1B)</mark>:
- A matrix $\mathbf{A}$ represents a <mark>linear transformation of a vector space</mark> (where $\mathbf{A} \in \mathbb{R}^{m \times n}$).
- Matrix-vector multiplication $\mathbf{v_{new}=Av}$ <mark>applies this transformation</mark> (encoded in $\mathbf{A}$) <mark>to a column vector</mark> $\mathbf{v}$ (where $\mathbf{v} \in \mathbb{R}^{n \times 1}$).
    - Note how inner dimensions match: $\mathbf{A} \in \mathbb{R}^{m \times n}$ and $\mathbf{v} \in \mathbb{R}^{n \times 1}$, therefore the result $\mathbf{v_{new}}$ will also be a column vector, albeit in $\mathbb{R}^{m \times 1}$.
- Elements of the resultant vector (let's call it $\mathbf{y=v_{new}}$) are given by: $$ y_i = \sum _{j=1}^{n}a_{ij}v_{j} $$
- <mark>**3B1B intuition for square matrices**</mark>: 
    - The new vector $\mathbf{v_{new}}$ will be a linear combination of the columns of $\mathbf{A}$ (i.e. where the basis vectors $\hat{i}$ and $\hat{j}$ **end up** in the new space)
    - with coefficients given by the elements of $\mathbf{v}$.
    - For non-square matrices see [this link](https://math.stackexchange.com/questions/1988948/geometric-interpretation-of-non-square-matrices)


In [3]:
# Multiply matrix A by (column) vector v = [2, 3]
A = np.array([[1, 7], [2, 3], [5, 0]])
v = np.array([[2], [3]])  # column vector
M = A @ v

print("Matrix vector multiplication: \nAv =\n", M)


Matrix vector multiplication: 
Av =
 [[23]
 [13]
 [10]]


### 4.2. Vector times matrix multiplication, $\mathbf{v}^\mathrm{T}\mathbf{A}$
- To multiply a (column) vector by a matrix, first transpose the vector $\mathbf{v}$ (i.e. make it a **row** vector $\mathbf{v}^\mathbf{T}$) to make the inner dimensions match.
    - Note how in $\mathbf{v_{new}=v}^\mathrm{T}\mathbf{A}$, inner dimensions match: $\mathbf{v}^\mathrm{T} \in \mathbb{R}^{1 \times m}$, and $\mathbf{A} \in \mathbb{R}^{m \times n}$ therefore the result $\mathbf{v_{new}}$ will also be a row vector in $\mathbb{R}^{1 \times n}$.
- Elements of the resultant vector (let's call it $\mathbf{y=v_{new}}$) are given by: $$y_{k}=\sum _{j=1}^{n}v_{j}a_{jk}$$
  

In [4]:
# Transpose the column vector v = [2, 3, 1], and multiply the resulting row vector v^T by matrix A
v = np.array([[2], [3], [1]])  # column vector
A = np.array([[1, 7], [2, 3], [5, 0]])
M = v.T @ A  # v.T is a row vector

print("Vector matrix multiplication: \nv^T A =", M[0])


Vector matrix multiplication: 
v^T A = [13 23]


### 4.3. Matrix times matrix Hadamard (element-wise) product, $A\odot B$:

- Definition (same as for vectors): Element-wise product on two matrices of same-dimension (i.e. $A, B\in \mathbb{R}^{m \times n}$)
- Elements of the resultant matrix are given by: $ (A\odot B)_{ij} = (A)_{ij}(B)_{ij} $. Example:

$$ \begin{bmatrix}2&3&1\\0&8&-2\end{bmatrix} \odot {\begin{bmatrix}3&1&4\\7&9&5\end{bmatrix}}={\begin{bmatrix}2\times 3&3\times 1&1\times 4\\0\times 7&8\times 9&-2\times 5\end{bmatrix}}={\begin{bmatrix}6&3&4\\0&72&-10\end{bmatrix}} $$


In [5]:
# Compute the Hadamard product of matrices A and B:
A = np.array([[2, 3, 1], [0, 8, -2]])
B = np.array([[3, 1, 4], [7, 9, 5]])
M = np.multiply(A, B)

print("Matrix Hadamard product: \nA ⊙ B =\n", M)


Matrix Hadamard product: 
A ⊙ B =
 [[  6   3   4]
 [  0  72 -10]]


### 4.4. Matrix times matrix multiplication, $\mathbf{AB}$ (use `np.dot(A,B)` to multiply)

The inner matrix dimensions of the two matrices (e.g. $\mathbf{A}$ and $\mathbf{B}$) **must match**. 
- $\mathbf{A}$ is of dimension $\mathbb{R}^{m \times p}$
- $\mathbf{B}$ is of dimension $\mathbb{R}^{p \times n}$ 
- Here, the dimension of size $p$ is the **inner matrix dimension**. 
    - If they match, it means # columns in $\mathbf{A}$ equals # rows in $\mathbf{B}$.
- Dimensions $m$ and $n$ are the **outer matrix dimensions**. Thus each element of $\mathbf{M=AB}$ can be computed as:

$$M_{ij} = \sum_{k=1}^p P_{ik}Q_{kj}$$

- <mark>I.e. (important)</mark> the $i,j$'th element of $\mathbf{M}$ is the dot product of the $i$'th row of $\mathbf{A}$ with $j$'th column of $\mathbf{Q}$

In [6]:
# Multiply A=[[1,7],[2,3],[5,0]] and B=[[2,6,3,1],[1,2,3,4]] -> [3x2] * [2x4] = output [3x4]

A = np.array([[1, 7], [2, 3], [5, 0]])
B = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print("A =\n", A)
print("\nB =\n", B)
print("\nAB =\n", np.dot(A, B))  # <-- inner dimensions match (p=2). output is a [3x4] matrix


A =
 [[1 7]
 [2 3]
 [5 0]]

B =
 [[2 6 3 1]
 [1 2 3 4]]

AB =
 [[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


In [7]:
# Multiplying B and A will raise a ValueError
np.dot(B, A)  # <-- inner dimensions don't match ...4] * [3...; Error


ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)