# Linear Algebra - Matrices (Pt 2)


## 1. Square matrices

A square matrices $\textbf{M}$ will have dimensions $n \times n$. (Thus, $\mathbf{M} \in \mathbb{R}^{n \times n}$)

### 1.1. Determinant, $\text{det}(\textbf{M})$
- The **Determinant**, $det(\textbf{M})$, is an important property of square matrices.
- <mark>**Geometric intuition of a determinant**</mark> (From 3B1B):
    - Its absolute value tells you how much an area increases/decreases after the transformation by matrix $\textbf{M}$
    - A **negative sign** tells you whether the vector space was "flipped" (i.e. if the basis vectors swapped sides)
    - <mark>**If the determinant is 0**</mark>, it means space has dropped **into fewer dimensions**
        - i.e. **at least 1 dimension is LOST*, so initial the area, volume, etc of the vector space is now 0
        - e.g. if a 2D matrix $\textbf{M}$ transforms areas into a 1D line (or a point), areas get squished to 0; hence $\text{det}(\textbf{M})=0$
- To prove understanding, explain: $\text{det}(\textbf{M}_1 \textbf{M}_2) = \text{det}(\textbf{M}_1) \text{det}(\textbf{M}_2)$

#### Formulae for calculating the determinant of a matrix $\textbf{M}$:

- For a $2 \times 2$ matrix; $det(\textbf{M})$ is:

$$
\begin{split}
|\textbf{M}| = \begin{bmatrix}
a & b \\
c & d\\
\end{bmatrix} = ad - bc\end{split}
$$


- For a $3 \times 3$ matrix; $det(\textbf{M})$ is:

$$
\begin{split}
% \begin{eqnarray*}
\begin{align*}
|\textbf{M}| = \begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{bmatrix} & = a\begin{bmatrix}
\Box &\Box  &\Box  \\
\Box & e & f \\
\Box & h & i \\
\end{bmatrix} - b\begin{bmatrix}
\Box &\Box  &\Box  \\
d & \Box & f \\
g & \Box & i \\
\end{bmatrix} + c\begin{bmatrix}
\Box &\Box  &\Box  \\
d & e & \Box \\
g & h & \Box \\
\end{bmatrix} \\
&&\\
& = a\begin{bmatrix}
e & f \\
h & i \\
\end{bmatrix} - b\begin{bmatrix}
d & f \\
g & i \\
\end{bmatrix} + c\begin{bmatrix}
d & e \\
g & h \\
\end{bmatrix} \\ 
&&\\
& = aei + bfg + cdh - ceg - bdi - afh
% \end{eqnarray*}
\end{align*}
\end{split}
$$

- For higher dimension matrices, a similar approach can be used.

### 1.2. Identity matrix

- A square matrix, $\textbf{I}$, with **ones on the diagonal** and **zeros everywhere else**
- Multiplying a matrix with $\textbf{I}$ (of compatible dimensionality) will produce the same matrix (like how $n \times 1 = n$)

In [1]:
# Find the determinant of M, and multiply M by np.eye(4) to demonstrate M x I = M

import numpy as np
from numpy.linalg import det

M = np.array([[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]])
print("M:\n", M)

print(f"Determinant: {det(M):.1f}")
I = np.eye(4)
print("\nI:\n", I)
print("\nM*I:\n", np.dot(M, I))


M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0

I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


## 2. Matrix inverse

For square matrices ($\mathbb{R}^{n\times n}$), $\textbf{M}^{-1}$ is the inverse of $\textbf{M}$ if $\textbf{M} \cdot \textbf{M}^{-1} = I$ (like how $3 \times \frac{1}{3} = 1$)

- A matrix $\mathbf{M}$ is considered **invertible** if it has an inverse $\mathbf{M}^{-1}$
    - **All** non-square matrices are **not** invertible
    - **Some** square matrices are also **not** invertible (i.e. singular matrices)
- The inverse of a matrix is unique: An invertible matrix **only has one inverse**.
- For a $2 \times 2$ matrix, the inverse is:
$$
\begin{split}
\textbf{M}^{-1} = \begin{bmatrix}
a & b \\
c & d\\
\end{bmatrix}^{-1} = \frac{1}{|\textbf{M}|}\begin{bmatrix}
d & -b \\
-c & a\\
\end{bmatrix}\end{split}
$$


### 2.1. Is it invertible?

- **Singular matrices** are those which have **no inverses** (like how 0 has no inverse)
    - $det(\textbf{M}) = 0$
- **Nonsingular matrices** are those which **do have an inverse**
    - $det(\textbf{M}) \ne 0$

In [2]:
# Recall, M has non-zero determinant so is invertible; but det(P)=0 so it can't be inverted

from numpy.linalg import inv

print(f"Determinant: {det(M):.1f}")
print("Inv M:\n", inv(M))

P = np.array([[0, 1, 0], [0, 0, 0], [1, 0, 1]])
print("det(p):", det(P))
print("Inv P:\n", inv(P))  # <-- LinAlgError thrown because P is Singular (not invertible)


Determinant: -38.0
Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
det(p): 0.0


LinAlgError: Singular matrix

### 2.2. Ill-Conditioned Matrices

- An ill-conditioned matrix is one which is **close to being singular** 
    - Its determinant will be close to 0 (problematic in the same way dividing by a tiny number is)
    - Computation errors (overflow, underflow, round-off errors) may occur
- **Condition number**: ***Higher number*** means the matrix is ***more*** ill-conditioned (i.e. closer to being singular)


In [3]:
# Compute the condition numbers, determinants, and matrix inverses for the following 3 matrices A_1, A_2, A_3

from numpy.linalg import cond

A_1 = np.array([[1, 1], [2, 3]])
A_2 = np.array([[4.1, 2.8], [9.7, 6.6]])
A_3 = np.array([[4.1, 2.8], [9.6760, 6.6080]])

print("\nMatrix A_1:")
print("Condition number(A_1):", cond(A_1))
print("det(A_1):", det(A_1))
print("Inv A_1:\n", inv(A_1))

print("\nMatrix A_2:")
print("Condition number(A_2):", cond(A_2))
print("det(A_2):", det(A_2))
print("Inv A_2:\n", inv(A_2))

print("\nMatrix A_3 -- This matrix is close to singular or badly scaled. It is ill-conditioned:")
print("Condition number(A_3):", cond(A_3))  # Note that the condition number is very high
print("det(A_3):", det(A_3))  # Note that the determinant is very close to zero
print("Inv A_3:\n", inv(A_3))  # Note that the inverse is very large



Matrix A_1:
Condition number(A_1): 14.933034373659225
det(A_1): 1.0
Inv A_1:
 [[ 3. -1.]
 [-2.  1.]]

Matrix A_2:
Condition number(A_2): 1622.9993838565622
det(A_2): -0.0999999999999999
Inv A_2:
 [[-66.  28.]
 [ 97. -41.]]

Matrix A_3 -- This matrix is close to singular or badly scaled. It is ill-conditioned:
Condition number(A_3): 1.1149221731402912e+16
det(A_3): -4.461167435465537e-15
Inv A_3:
 [[-1.53781451e+15  6.51616316e+14]
 [ 2.25179981e+15 -9.54152463e+14]]


### 2.3. Trace 

- The **trace** of $\textbf{A} : \textbf{A} \in \mathbb{R}^{n\times n}$ is the sum of elements on the main diagonal (from left to right):

$$ \text{tr}(\textbf{A}) = \sum_{i=1}^{n} a_{ii} $$


In [4]:
# Compute the trace of the following matrix A

from numpy import trace

A = np.array([[4.1, 2.8], [9.7, 6.6]])
print("Trace(A)", trace(A))


Trace(A) 10.7


## 3. Back to non-square matrices

### 3.1. Rank

- The **rank** of $\textbf{A} : \textbf{A} \in \mathbb{R}^{m\times n}$ is the **number of linearly independent columns or rows** in $\textbf{A}$
    - NB: Num. of lin. indep. cols. in a matrix $\equiv$ Num. of lin. indep. rows in that matrix

#### 3.1.1. "Full Rank" Matrix

- $\textbf{A}$ is **full rank** if $\text{rank}(\textbf{A}) = \min(m,n)$
- $\textbf{A}$ is also full rank if **all its columns are linearly independent**

#### 3.1.2. Augmented Matrix

- If vector $\textbf{y}$ is concatenated to matrix $\textbf{A}$, we say "$\textbf{A}$ augmented with $\textbf{y}$". Denoted as $(\textbf{A}\vert \textbf{B})$.
    - if $\text{rank}((\textbf{A}\vert \textbf{B})) = \text{rank}(\textbf{A})+1$, then vector $\textbf{y}$ is **"new" information**
    - otherwise, if $\text{rank}((\textbf{A}\vert \textbf{B})) = \text{rank}(\textbf{A})$,  it means $\textbf{y}$ can be created as a linear combination of the columns in $\textbf{A}$

In [5]:
# Compute the condition number and rank for matrix A = [[1,1,0],[0,1,0],[1,0,1]]
# If y = [[1],[2],[1]], get the augmented matrix [A,y]

from numpy import trace
from numpy.linalg import cond, matrix_rank

A = np.array([[1, 1, 0], [0, 1, 0], [1, 0, 1]])
y = np.array([[1], [2], [1]])
print("A matrix's shape:", A.shape, "\ny vector's shape", y.shape)

print("\nCondition number(A):", cond(A))
print("Rank(A):", matrix_rank(A))
print("Trace(A):", trace(A))

A_y = np.concatenate((A, y), axis=1)
print("\nOriginal A matrix:\n", A, "\ny vector:\n", y, "\n\nAugmented (A|y) matrix:\n", A_y)
print("Rank(A_y):", matrix_rank(A_y))

print("\nNote that the rank of A and A_y are both 3, so y is a linear combination of the columns of A.")
print("Therefore, there is no new information in y that is not already in A.")


A matrix's shape: (3, 3) 
y vector's shape (3, 1)

Condition number(A): 4.048917339522305
Rank(A): 3
Trace(A): 3

Original A matrix:
 [[1 1 0]
 [0 1 0]
 [1 0 1]] 
y vector:
 [[1]
 [2]
 [1]] 

Augmented (A|y) matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]
Rank(A_y): 3

Note that the rank of A and A_y are both 3, so y is a linear combination of the columns of A.
Therefore, there is no new information in y that is not already in A.


# 4. 3Blue1Brown's aside
## A few useful transformations

### Vector Transformations

### Matrix Transformations (TBC double check)

$$ \begin{align*} 
\text{No change (Identity matrix)} &: \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Translation} &: \text{NA} &\text{in 3D:} \begin{bmatrix} 1 & 0 & X \\ 0 & 1 & Y \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Scaling (about origin)} &: \begin{bmatrix} W & 0 \\ 0 & H \end{bmatrix} &\text{in 3D:} \begin{bmatrix} W & 0 & 0 \\ 0 & H & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Rotation (about origin)} &: \begin{bmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{bmatrix} &\text{in 3D:} \begin{bmatrix} \cos\theta & -\sin\theta & 0 \\ \sin\theta & \cos\theta & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Shear (in x-direction)} &: \begin{bmatrix} 1 & \tan\phi \\ 0 & 1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} 1 & \tan\phi & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Shear (in y-direction)} &: \begin{bmatrix} 1 & 0 \\ \tan\psi & 1 \end{bmatrix} &\text{in 3D:}\begin{bmatrix} 1 & 0 & 0 \\ \tan\psi & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Reflect (about origin)} &: \begin{bmatrix} -1 & 0 \\ 0 & -1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} -1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Reflect (about x-axis)} &: \begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} 1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Reflect (about y-axis)} &: \begin{bmatrix} -1 & 0 \\ 0 & 1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} -1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\end{align*} $$