In [1]:
import numpy as np # more basic functionality
import scipy # advanced functionality, built on numpy
import matplotlib as mpl
import matplotlib.pyplot as plt

## More terminology:

### Spans and spaces

- **Span**: The span of a set of vectors is all linear combinations of those vectors
- **Vector space** is denoted as $\mathbb{R}^n$. 
    - Every element in a vector space can be written as a **linear combination** of the elements in the **basis** (unit) vectors
        - **Basis (unit) vectors** (example): For a 2D vector space, the basis vectors are $\hat{i} = \begin{bsmallmatrix} 1 \\ 0 \end{bsmallmatrix}$ and $\hat{j} = \begin{bsmallmatrix} 0 \\ 1 \end{bsmallmatrix}$
        - A matrix $A$ applies a linear transformation to a vector space (i.e. all vectors in the space)
        - <mark>The columns of $A$ represent the **landing points** for the basis (unit) vectors **after the transformation**</mark>
        - By extension, $A$ moves **every input vector** (more precisely, the **point where every vector's tip is**) **linearly** to a new location.
        - We only need to know how $A$ transforms the bases $\hat{i}$ and $\hat{j}$, since
            - any vector $v$ is <mark>just a **linear combination** of $\hat{i}$ and $\hat{j}$ **both before and after being transformed by $A$**</mark>
- **Subspace**: a subset of a larger vector space
    - **Column space**: Span of all column vectors of of matrix $A$
    - **Row space**: Span of all row vectors of matrix $A$
    - **Null space**: If $A \cdot x = 0$, the span of all solutions $x$ constitutes the **null space** of $A$
    - **Left-Null space**: If $A^T \cdot x = 0$, the span of all solutions $x$ constitutes the **left-null space** of $A$
    
### More properties

- **Rank**: The number of **linearly independent** columns (or rows) in $A$ is its rank
- **Orthonormal vectors**: Two unit length vectors whose inner (i.e. dot) products are 0
- **Real value matrices**:
    - **Orthogonal matrices**: If $A$'s rows and cols are orthonormal vectors, $A$ is an orthogonal matrix. It satisfies:
        - $A^TA = AA^T = I$
    - **Symmetric matrix**: where $A^T = A$ (square matrices only) 
- **Complex value matrices**
    - Hermitian matrix: Complex matrices' analog to orthogonal matrix
    - Unitary matrix: Complex matrices' analog to symmetric matrix
- **Determinant**: This can be computed for any square matrix $A$
    - Matrices are only invertible if $det(A) \ne 0$. Such matrices are **non-singular**; and satisfy $AA^{-1}=I$
    - Matrices where $det(A) = 0$ are not invertible. They are **singular** matrices
  
#### Examples of the above (where relevant):

- The **span** of vectors (0,1) and (1,0) is the whole x-y plane
- A vector, $v$, with 3 elements is said to exist in **vector space** $\mathbb{R}^3$
- The $\mathbb{R}^3$ vector, $v$ is composed of **basis vectors** (1,0,0), (0,1,0), and (0,0,1).
- The subspace of a 3D vector (in $\mathbb{R}^3$) is the span of vectors (1,0,0) and (0,1,0) 
    - in this case the 2D x-y plane is a subspace (subset) of the 3D x,y,z vector space
- Vectors (1,2,3) and (10,20,30) are linearly dependent since one is a multiple of the other.
    - A matrix with those two vectors would be rank 1

### Recap: A few ways to multiply vectors

In [2]:
# Find the inner and outer products of two 1D arrays (not exactly vectors, no double [[]])
a = np.array([4,5,6])
b = np.array([7,8,9])

print('Types of vector multiplication')
print('inner:', np.inner(a,b)) # dot prod; dims are: [1x3][3x1]=[1x1] <-- output dim
print('outer:', np.outer(a,b)) # dims are [3x1][1x3]=[3x3] <-- output dim
print('hadamard:', a * b) # elementwise (or hadamard) product

Types of vector multiplication
inner: 122
outer: [[28 32 36]
 [35 40 45]
 [42 48 54]]
hadamard: [28 40 54]


### Gram-Schmidt Process

Use this to orthonormalise anything (vector or matrix (orthogonalise))

- Orthonormalise a set of vectors $\{\bar{v_1}, \bar{v_2}, \bar{v_3}, ..., \bar{v_n}\}$ 
    - to $\{\bar{u_1}, \bar{u_2}, \bar{u_3}, ..., \bar{u_n}\}$, where each $u$ vector is in the same $\mathbb{R}^n$ vector space, 
        - but each vector is unit length, and 
        - is mutually orthogonal with other vectors

I.e. Transform a set of vectors into a set of orthonormal vectors in the same vector space

## Matrix decompositions

### Gaussian Elimination (or Decomposition?)

- **Purpose**: We use Gaussian Elimination to simplify a system of linear equations, $Ax=b$ into *row echelon form* (or *reduced row echelon form*; which allows solving $Ax=b$ by simple inspection)
- Application: 
    - Solving linear system $Ax=b$, 
    - Computing inverse matrices
    - Computing rank
    - Computing determinant
    - **Elementary row operations**: Methods by which the above are done
        - Swapping rows
        - Scaling rows
        - Adding rows to each other (i.e. creating linear combinations)
        
- **Row echelon form**: The first *non-zero* element from the left in each row (aka leading coefficient, pivot) is **always to the right of** the first *non-zero* element in the row above
- **Reduced row echelon form**: Row echelon form whose pivots are $1$ and column containing pivots are $0$ elsewhere

- Elementary row operation

### LU Decomposition

Like Gaussian Decomposition, but more computationally efficient

Decompose any matrix $A$ (square or not) into:
- A lower triangular matrix $L$
- An upper triangular matrix $U$
- Sometimes needing to reorder $A$ using a $P$ matrix

In [3]:
a = np.random.randn(3,4)
print('A:\n', a)

p,l,u = scipy.linalg.lu(a)
print('\nP:\n', p)
print('\nL:\n', l)
print('\nU:\n', u)
print('\n----\n\nRecomposition: PLU = A:\n', p@l@u)

A:
 [[-0.55038208 -1.64274921  0.74248386  1.05567946]
 [-0.37105223  1.64296612 -0.9953272   1.42100597]
 [-0.88663242  1.07443251  1.56042151  0.51827791]]

P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

L:
 [[ 1.          0.          0.        ]
 [ 0.62075565  1.          0.        ]
 [ 0.41849612 -0.51665389  1.        ]]

U:
 [[-0.88663242  1.07443251  1.56042151  0.51827791]
 [ 0.         -2.30970927 -0.22615661  0.73395552]
 [ 0.          0.         -1.76520225  1.58330965]]

----

Recomposition: PLU = A:
 [[-0.55038208 -1.64274921  0.74248386  1.05567946]
 [-0.37105223  1.64296612 -0.9953272   1.42100597]
 [-0.88663242  1.07443251  1.56042151  0.51827791]]


### QR Decomposition

Decompose a matrix $A$ into:
- an orthogonal matrix $Q$
- an upper triangular matrix $R$

It's used in QR algorithms to solve the linear least square problem. 

Also, the $Q$ matrix is sometimes what we desire after the **Gram-Schmidt process**

In [4]:
a = np.random.randn(3,4)
print('A:\n', a)

q,r = np.linalg.qr(a)
print('\nQ:\n', q)
print('\nR:\n', r)
print('\n----\n\nRecomposition: QR = A:\n', q@r)

A:
 [[-1.33656849  0.47121422  0.84715639 -1.63111615]
 [ 1.0110986   0.73512738 -0.23842762  0.01694656]
 [-0.4905946  -0.94730809  0.71554459  0.96648081]]

Q:
 [[-0.76538983 -0.58201376  0.27466052]
 [ 0.57900855 -0.43644523  0.68866876]
 [-0.28094042  0.68613086  0.67104167]]

R:
 [[ 1.74625851  0.33111959 -0.98748191  0.98672838]
 [ 0.         -1.2450733   0.10196114  1.6050681 ]
 [ 0.          0.          0.548643    0.21221625]]

----

Recomposition: QR = A:
 [[-1.33656849  0.47121422  0.84715639 -1.63111615]
 [ 1.0110986   0.73512738 -0.23842762  0.01694656]
 [-0.4905946  -0.94730809  0.71554459  0.96648081]]


### Cholesky Decomposition

Decompose a symmetric (or Hermitian) positive-definite matrix into:

- a lower triangular matrix $L$
- and its transpose (or conjugate transpose) $L.H.$

Used in algorithms for numerical convenience

In [5]:
x = np.diagflat([[1,2], [3,4]])
print('x:\n', x)

L = np.linalg.cholesky(x)
print('\nL:\n', L)

print('\n----\n\nRecomposition: LL^T:\n', L @ L.T)

x:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

L:
 [[1.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.        ]
 [0.         0.         1.73205081 0.        ]
 [0.         0.         0.         2.        ]]

----

Recomposition: LL^T:
 [[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


# Questions

- When exactly do we use decompositions?