# Linear Algebra - Vectors

## 1. Vectors

### Notation:
- A vector, $\textbf{v}$, is a list of numbers (scalars) arranged in a particular order.
- By convention, vectors are implicitly **column vectors**. So $\textbf{v} \in \mathbb{R}^{n}$; or implicitly $\textbf{v} \in \mathbb{R}^{n \times 1}$.
- To represent a column vector, $\textbf{v}$, as a **row vector**, take its **transpose** $\textbf{v}^\mathrm{T}$. Hence, $\textbf{v}^\mathrm{T} \in \mathbb{R}^{1 \times n}$.
    - **Transpose** operation turns a column vector into a row vector vice versa. For matrices, it swaps rows and columns.
- The $i$'th element of vector $\textbf{v}$ is denoted $v_i$.

### Properties and geometric interpretation of a vector:
- The number of elements in a vector is called its **dimension**. This also tells us the vector space it belongs to.
    - For example, $\textbf{v} \in \mathbb{R}^{3}$ is an 3-dimensional vector.
- A vector can be thought of as an arrow in n-dimensional space.
- The **magnitude** of a vector is its **length** in n-dimensional space. (many distance formulas can be used to compute):
    - $L_2$ norm (Euclidean length): $\Vert\textbf{v}\Vert_2 = \sqrt{\Sigma_i w_{i}^{2}}\quad$ (*physical length* of a vector in n-dim space)
    - $L_1$ norm (Manhattan Distance): $\Vert\textbf{v}\Vert_1 = \Sigma_i |v_i|\quad $
    - More generally, 
        - The **p-norm** is $\Vert v \Vert_{p} = \sqrt[p]{(\sum_i v_i^p)}$
        - And the $L_\infty$ norm, $\Vert\textbf{v}\Vert_\infty$, is the $p$-norm where $p=\infty$
    - Generally the $L_2$ norm is implied when referring to vector length. 
      - Hence $\Vert\textbf{v}\Vert_2$ can be written more simply as $\Vert\textbf{v}\Vert$ or occasionally $|\textbf{v}|$ (though the latter is ambiguous with the absolute value of a scalar)

In [1]:
import numpy as np

# Create a row vector and a column vector, show their shapes
row_vec = np.array([[1, -5, 3, 2, 4]])
col_vec = np.array([[1], [2], [3], [4]])

# Comments show output if you don't use list of lists
print("row_vec =", row_vec[0], "\nrow_vec shape:", row_vec.shape)  # [ 1 -5  3  2  4] and (1, 5)
print("\ncol_vec =\n", col_vec, "\ncol_vec shape:", col_vec.shape)  # [1 2 3 4] and (4, 1)


row_vec = [ 1 -5  3  2  4] 
row_vec shape: (1, 5)

col_vec =
 [[1]
 [2]
 [3]
 [4]] 
col_vec shape: (4, 1)


In [2]:
# Transpose row_vec and calculate L1, L2, and L_inf norms
from numpy.linalg import norm

print("row_vec =", row_vec[0], "\nrow_vec shape:", row_vec.shape)

transposed_row_vec = row_vec.T  # now a column vector
print("\ntransposed_row_vec =", transposed_row_vec, "\ntransposed_row_vec shape:", transposed_row_vec.shape, "\n")

norm_1 = norm(transposed_row_vec, 1)
norm_2 = norm(transposed_row_vec, 2)  # <- L2 norm is default and most common
norm_inf = norm(transposed_row_vec, np.inf)

print("Measures of magnitude:")
print(f"L_1 norm is: {norm_1:.1f}")
print(f"L_2 norm is: {norm_2:.1f}", "(most common)")
print(f"L_inf norm is: {norm_inf:.1f}", "(absolute value of largest element)")  # NB: norm_inf = |largest element|


row_vec = [ 1 -5  3  2  4] 
row_vec shape: (1, 5)

transposed_row_vec = [[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]] 
transposed_row_vec shape: (5, 1) 

Measures of magnitude:
L_1 norm is: 15.0
L_2 norm is: 7.4 (most common)
L_inf norm is: 5.0 (absolute value of largest element)


## 2. Vector addition, $\textbf{v} + \textbf{w}$

Elementwise addition; if vectors are of of same length (i.e. if $\textbf{v}$ and $\textbf{w}$ are both in $\mathbb{R}^n$) then:

- **Addition of 2 vectors**: $\textbf{u} = \textbf{v} + \textbf{w}$ is the vector with elements $u_i = v_i + w_i$


In [3]:
# Sum vectors v = [10, 9, 3] and w = [2, 5, 12]
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])

print("Vector addition: \npy: v + w =", (v + w)[0])


Vector addition: 
py: v + w = [12 14 15]


## 3. Scalar times vector, $\alpha\textbf{v}$

To multiply a vector $\textbf{v}$, by a scalar $\alpha$ (a number in $\mathbb{R}$), do it "elementwise" or "pairwise".

- **Scalar multiplication of a vector**: $\textbf{u} = \alpha \textbf{v}$ is the vector with elements $u_i = \alpha v_i$

In [4]:
# Multiply vector v = [10, 9, 3] by scalar alpha = 4
v = np.array([[10, 9, 3]])
alpha = 4

print("Scalar times vector: \npy: alpha * v =", (alpha * v)[0])


Scalar times vector: 
py: alpha * v = [40 36 12]


### 3.1. Linear Combinations

- A **linear combination** of set $S$ is defined as $\Sigma \alpha_i s_i$
    - Here $\alpha_i$ values are the **coefficients** of $s_i$ values
    - Example: Grocery bill total cost is a linear combination of items purchased:
        - $\displaystyle{\sum c_i n_i}$ ($c_i$ is item cost, $n_i$ is qty. purchased)
    
### 3.2. Linear Dependence and Independence
    
- A set is **linearly INdependent** if no object in the set can be written as a lin. combination of the other objects in the set.
    - Example: $\textbf{v} = [1, 1, 0], \textbf{w} = [1, 0, 0]$ and $\textbf{u} = [0, 0, 1]$ are <mark>linearly independent. Can you see why?</mark>

#### 3.2.1. <mark>Geometric interpretation</mark>: 

- If two vectors are linearly dependent, they lie on the same line/plane/hyperplane in n-dimensional space.
    - For a 2D vector space, if two vectors are linearly dependent, they lie on the same line (1D subspace).
    - For a 3D vector space, if two vectors are linearly dependent, they lie on the same plane (2D subspace).
    - And so on...

#### 3.2.2. Example:
Below is an example of a **linearly DEpendent** set. $\textbf{x}$ is dependent on 

In [5]:
# Writing the vector x = [-8, -1, 4] as a linear combination of 3 vectors, v, w, and u:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])

x = 3 * v - 2 * w + 4 * u
print("x is a linear combination of v, w, and u. It is linearly dependent on them: \nx =", x[0])


x is a linear combination of v, w, and u. It is linearly dependent on them: 
x = [-8 -1  4]


## 4. Vector multiplication (4 approaches)

### 4.1. Vector dot (inner) product, $\textbf{v} \cdot \textbf{w}$

Geometric interpretation: <mark>A measure of how similarly directed two vectors are</mark> (think shadows, or projections)

- Definition: $\textbf{v} \cdot \textbf{w} = \Sigma_{i=1}^n v_i w_i$
    - It's the sum of elementwise products. For $\textbf{v}, \textbf{w} \in \mathbb{R}^n$, 
- Note also, since $\textbf{v}, \textbf{w} \in \mathbb{R}^n$, transpose to make inner dimensions match. Dot product can hence be rewritten as:
    - $\textbf{v} \cdot \textbf{w} = \textbf{v}^\mathrm{T}\textbf{w}$

#### Angle between vectors, $\theta$

- Think of dot product as "**degree of alignment**": $\textbf{v} \cdot \textbf{w} = \Vert\textbf{v}\Vert\:\Vert\textbf{w}\Vert \cos \theta$
    - (1,1) and (2,2) are **parallel**; computing the angle gives $\theta = 0$
    - (1,1) and (-1,1) are **orthogonal** (perpendicular) bc $\theta = \pi/2$ and $\textbf{v} \cdot \textbf{w} = 0$ (no alignment)

* Extending on the dot product idea, $\textbf{v} \cdot \textbf{w}$, the **angle between two vectors** is $\theta$. It is as defined by the formula:
$$ \theta = \arccos \left({\frac {\textbf{v} \cdot \textbf{w}}{\left\|\textbf{v}\right\|\left\|\textbf{w} \right\|}}\right) $$

#### Recap: Many ways to express a dot product (it's commutative!):

$$ 
\begin{align*}

\textbf{v} \cdot \textbf{w} = \Sigma_{i=1}^n v_i w_i &= \textbf{v}^\mathrm{T}\textbf{w} = \Vert\textbf{v}\Vert\:\Vert\textbf{w}\Vert \cos \theta \\
& = \textbf{w}^\mathrm{T}\textbf{v} = \Vert\textbf{w}\Vert\:\Vert\textbf{v} \Vert \cos \theta = \textbf{w} \cdot \textbf{v}

\end{align*}
$$


In [6]:
# Compute the dot (i.e. inner) product of vectors v = [10, 9, 3] and w = [2, 5, 12]
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])

print("Vector dot product: v • w:")
print(
    "py: np.dot(v, w.T) =", np.dot(v, w.T)[0][0]
)  # w.T to match inner dims, manually need to transpose w to column vector

# Compute the angle between vectors v and w
theta = np.arccos(u / (norm(v) * norm(w)))  # norm() default is L2
print("\nTheta =", theta[0][0])

# These methods produce the same result as np.dot(v, w)
print("\n----------------- Below methods produce same dot prod -----------------\n")
print("py: np.inner(v, w) =", np.inner(v, w)[0][0])  # same as dot, but more explicit. Can be used for higher dims.
print("py: np.matmul(v, w.T) =", np.matmul(v, w.T)[0][0])  # Assumes all inputs are row vectors
print("py: v @ w.T =", (v @ w.T)[0][0])  # @ operator is equivalent to np.matmul() for 2D arrays


Vector dot product: v • w:
py: np.dot(v, w.T) = 101

Theta = 1.5707963267948966

----------------- Below methods produce same dot prod -----------------

py: np.inner(v, w) = 101
py: np.matmul(v, w.T) = 101
py: v @ w.T = 101


### 4.2. Vector outer product, $\textbf{v} \otimes \textbf{w}$

- Definition: $\textbf{v} \otimes \textbf{w}$ is the $m \times n$ matrix $\textbf{A}$ obtained by multiplying each element of $\textbf{v}$ by each element of $\textbf{w}$.
    - Unlike with the dot product, here the vectors $\textbf{v}$ and $\textbf{w}$ may have different lengths: $\textbf{v} \in \mathbb{R}^{m\times 1}$, $ \textbf{w} \in \mathbb{R}^{n\times 1}$.
    - Elements of the resultant matrix are given by: $ (\textbf{v} \otimes \textbf{w} )_{ij}=v_{i}w_{j} $
    - The entire matrix is represented as: $$ \textbf {v} \otimes \textbf {w} =\textbf {A} ={\begin{bmatrix}v_{1}w_{1}&v_{1}w_{2}&\dots &v_{1}w_{n}\\v_{2}w_{1}&v_{2}w_{2}&\dots &v_{2}w_{n}\\\vdots &\vdots &\ddots &\vdots \\v_{m}w_{1}&v_{m}w_{2}&\dots &v_{m}w_{n}\end{bmatrix}} $$

- Note also, since $\textbf{v}$ and $\textbf{w}$ are column vectors ($\textbf{v} \in \mathbb{R}^{m\times 1}$, $ \textbf{w} \in \mathbb{R}^{n\times 1}$), we can transpose $\textbf{w}^\textrm{T}$ (now a row vector, $ \textbf{w}^\mathrm{T} \in \mathbb{R}^{1\times n}$). 
    - $\textbf{v} \otimes \textbf{w}$ is hence equivalent to the matrix multiplication $\textbf{v}\textbf{w}^\textrm{T}$ (since this ensures the inner dimensions ($1$) to match). Example: $$ \textbf {v} \otimes \textbf {w} =\textbf {v} \textbf {w} ^{\textsf {T}}={\begin{bmatrix}v_{1}\\v_{2}\\v_{3}\\v_{4}\end{bmatrix}}{\begin{bmatrix}w_{1}&w_{2}&w_{3}\end{bmatrix}}={\begin{bmatrix}v_{1}w_{1}&v_{1}w_{2}&v_{1}w_{3}\\v_{2}w_{1}&v_{2}w_{2}&v_{2}w_{3}\\v_{3}w_{1}&v_{3}w_{2}&v_{3}w_{3}\\v_{4}w_{1}&v_{4}w_{2}&v_{4}w_{3}\end{bmatrix}} $$

In [7]:
# Compute the outer product of same vectors v = [10, 9, 3] and w = [2, 5, 12]
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
# w = np.array([[2, 5, 12, 13]])  # <- uncomment to see outer product with different dimensions

print("Vectors:\nv =", v[0], "\nw =", w[0])
print("\nVector inner product, v • w\npy: np.inner(v, w) =", np.inner(v, w)[0][0])  # As previous code cell
print("\nVector outer product, v ⨂ w\nnp.outer(v, w) =\n", np.outer(v, w))  # Assumes all inputs column vectors
print("\nVector outer product flipped, w ⨂ v\nnp.outer(w, v) =\n", np.outer(w, v))  # Assumes all inputs column vectors


Vectors:
v = [10  9  3] 
w = [ 2  5 12]

Vector inner product, v • w
py: np.inner(v, w) = 101

Vector outer product, v ⨂ w
np.outer(v, w) =
 [[ 20  50 120]
 [ 18  45 108]
 [  6  15  36]]

Vector outer product flipped, w ⨂ v
np.outer(w, v) =
 [[ 20  18   6]
 [ 50  45  15]
 [120 108  36]]


### 4.3. Vector Hadamard (element-wise) product, $\textbf{v}\odot \textbf{w}$:

- Definition: Element-wise product, where the vectors **must be of the same dimension**
    - This method also works for matrices of the same dimension.
    - Output vector/matrix is of the same dimension as the operands.
- Notation: $\textbf{v}\odot \textbf{w}$ (sometimes $\textbf{v}\circ \textbf{w}$)
    - Elements of the resultant vector are given by: $ (\textbf{v}\odot \textbf{w})_{i} = (\textbf{v})_{i}(\textbf{w})_{i} $
- Example:

$$ \begin{bmatrix}2&3&1\end{bmatrix} \odot {\begin{bmatrix}3&1&4\end{bmatrix}}={\begin{bmatrix}2\times 3&3\times 1&1\times 4\end{bmatrix}}={\begin{bmatrix}6&3&4\end{bmatrix}} $$

In [8]:
# Compute the Hadamard product of vectors v = [2, 3, 1] and w = [3, 1, 4]
v = np.array([[2, 3, 1]])
w = np.array([[3, 1, 4]])

print("Vector Hadamard product: v ⊙ w:\npy: np.multiply(v, w) =", np.multiply(v, w)[0])


Vector Hadamard product: v ⊙ w:
py: np.multiply(v, w) = [6 3 4]


### 4.4. Vector cross product, $\textbf{v}\times \textbf{w}$

Geometric interpretation: The cross product $\textbf{v} \times \textbf{w}$ is <mark>a vector perpendicular to both</mark> $\textbf{v}$ <mark>and</mark> $\textbf{w}$, <mark>whose length equals the area enclosed by the parallelogram created by the two vectors</mark>

- Cross product definition: 
$$\textbf{v} \times \textbf{w} = \Vert \textbf{v} \Vert \: \Vert \textbf{w} \Vert\sin{(\theta)} \, \textbf{n}$$
- Where: 
    - $\theta$ can by computed via dot product
    - $\textbf{n}$ is a unit vector (i.e. length $1$) perpendicular to both $\textbf{v}$ and $\textbf{w}$.

In [9]:
# Compute the cross product of v = [0,2,0] and w = [3,0,0]
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])

print("Vector cross product: v ⨉ w\nnp.cross(v, w) =", np.cross(v, w)[0])


Vector cross product: v ⨉ w
np.cross(v, w) = [ 0  0 -6]
