# Linear Algebra - Matrices (Pt 3)


## 1. Square matrices

- A square matrix $\textbf{M}$ has dimensions $n \times n$. (Thus, $\mathbf{M} \in \mathbb{R}^{n \times n}$)
- Square matrices linearly transform all vectors in an $\mathbb{R}^n$ vector space to $\mathbb{R}^n$ vector space (i.e. no dimensionality change).
    - This means the vector space is transformed in a way that <mark>no dimensions are added or lost</mark>. 
    - Also, the origin remains fixed, and all grid lines remain parallel and evenly spaced.

## 2. Determinant, $\text{det}(\textbf{M})$ or $|\textbf{M}|$
- The **Determinant**, $\text{det}(\textbf{M})$ or $|\textbf{M}|$, is an important property of square matrices.

### 2.1. <mark>Geometric intuition</mark> (From 3Blue1Brown):
- Its absolute value, $\vert{\text{det}(\textbf{M})}\vert$, tells you the **factor by which any and all regions in the vector space increases/decreases** after the transformation by matrix $\textbf{M}$
- A "region" can be thought of as depending on the dimensionality of the vector space:
    - For a 2D vector space, a "region" is an area (e.g. of the unit square)
    - For a 3D vector space, a "region" is a volume (e.g. of the unit cube)
    - And so on...
- How to interpret the determinant in terms of **initial** region (area/volume/etc) in the vector space (before transformation):
    - Absolute values:
        - If $\vert{\text{det}(\textbf{M})}\vert > 1$: Any/all initial regions in the vector space are **scaled up** by that factor
        - If $\vert{\text{det}(\textbf{M})}\vert = 1$: Any/all initial regions in the vector space **do not change in size**
        - If $0 < \vert{\text{det}(\textbf{M})}\vert < 1$: Any/all initial regions in the vector space **shrink** by that factor
    - If ${\text{det}(\textbf{M})} = 0$: it means space has <mark>dropped **into fewer dimensions**</mark> (i.e. information lost)
        - i.e. **at least 1 dimension is LOST**, so all initial regions (area/volume/etc) of the vector space is now 0
        - e.g. if a 2D matrix $\textbf{M}$ transforms a 2D vector space into a 1D line (or a 0D point), all "areas" in the original 2D vector space no longer exist. They are squished to 0; hence $\text{det}(\textbf{M})=0$
        - This also means that the columns of $\textbf{M}$ are linearly dependent (i.e. they lie on the same line/plane/etc)
    - If ${\text{det}(\textbf{M})} < 0$
        - A **negative sign** tells you whether the vector space was "flipped" (i.e. if the basis vectors swapped sides).
        - Here, $\textbf{M}$ is said to "invert the orientation" of the vector space.
    

- To prove understanding, explain: $\text{det}(\textbf{M}_1 \textbf{M}_2) = \text{det}(\textbf{M}_1) \text{det}(\textbf{M}_2)$

### 2.2. Formulae for calculating the determinant of a matrix $\textbf{M}$:

- For a $2 \times 2$ matrix; $\text{det}(\textbf{M})$ is:

$$
\begin{split}
|\textbf{M}| = \begin{bmatrix}
a & b \\
c & d\\
\end{bmatrix} = ad - bc\end{split}
$$


- For a $3 \times 3$ matrix; $\text{det}(\textbf{M})$ is:

$$
\begin{split}
% \begin{eqnarray*}
\begin{align*}
|\textbf{M}| = \begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{bmatrix} & = a\begin{bmatrix}
\Box &\Box  &\Box  \\
\Box & e & f \\
\Box & h & i \\
\end{bmatrix} - b\begin{bmatrix}
\Box &\Box  &\Box  \\
d & \Box & f \\
g & \Box & i \\
\end{bmatrix} + c\begin{bmatrix}
\Box &\Box  &\Box  \\
d & e & \Box \\
g & h & \Box \\
\end{bmatrix} \\
&&\\
& = a\begin{bmatrix}
e & f \\
h & i \\
\end{bmatrix} - b\begin{bmatrix}
d & f \\
g & i \\
\end{bmatrix} + c\begin{bmatrix}
d & e \\
g & h \\
\end{bmatrix} \\ 
&&\\
& = aei + bfg + cdh - ceg - bdi - afh
% \end{eqnarray*}
\end{align*}
\end{split}
$$

- For higher dimension matrices, a similar approach can be used.

#### 2.2.1 Geometric derivation of the $2 \times 2$ determinant formula:

<p align="center">
    <img src="images/determinant.png" alt="2D Determinant" width="600"/>
</p>

- This relies on how the square matrix $\textbf{M}$ transforms the unit square in $\mathbb{R}^2$ into a parallelogram in $\mathbb{R}^2$.
- See [A Few Useful Transformations](#a-few-useful-transformations) section for a recap of how each element of the matrix $\textbf{M}$ affects the transformation of the unit square.


### 2.3. Identity matrix

- A square matrix, $\textbf{I}$, with **ones on the diagonal** and **zeros everywhere else**
- Multiplying a matrix with $\textbf{I}$ (of compatible dimensionality) will produce the same matrix (like how $n \times 1 = n$)

In [1]:
# Find the determinant of M, and multiply M by np.eye(4) to demonstrate M x I = M

import numpy as np
from numpy.linalg import det

M = np.array([[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]])
print("M:\n", M)

print(f"Determinant: {det(M):.1f}")
I = np.eye(4)
print("\nI:\n", I)
print("\nM @ I:\n", M @ I)


M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0

I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

M @ I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


## 3. Trace 

- The **trace** of $\textbf{A} : \textbf{A} \in \mathbb{R}^{n\times n}$ is the sum of elements on the main diagonal (from left to right):

$$ \text{tr}(\textbf{A}) = \sum_{i=1}^{n} a_{ii} $$


In [2]:
# Compute the trace of the following matrix A

from numpy import trace

A = np.array([[4.1, 2.8], [9.7, 6.6]])
print("Trace(A)", trace(A))


Trace(A) 10.7


# 3. 3Blue1Brown's aside
## A few useful transformations

### Vector Transformations

### Matrix Transformations (TBC double check)

$$ \begin{align*} 
\text{No change (Identity matrix)} &: \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Translation} &: \text{NA} &\text{in 3D:} \begin{bmatrix} 1 & 0 & X \\ 0 & 1 & Y \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Scaling (about origin)} &: \begin{bmatrix} W & 0 \\ 0 & H \end{bmatrix} &\text{in 3D:} \begin{bmatrix} W & 0 & 0 \\ 0 & H & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Rotation (about origin)} &: \begin{bmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{bmatrix} &\text{in 3D:} \begin{bmatrix} \cos\theta & -\sin\theta & 0 \\ \sin\theta & \cos\theta & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Shear (in x-direction)} &: \begin{bmatrix} 1 & \tan\phi \\ 0 & 1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} 1 & \tan\phi & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Shear (in y-direction)} &: \begin{bmatrix} 1 & 0 \\ \tan\psi & 1 \end{bmatrix} &\text{in 3D:}\begin{bmatrix} 1 & 0 & 0 \\ \tan\psi & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Reflect (about origin)} &: \begin{bmatrix} -1 & 0 \\ 0 & -1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} -1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Reflect (about x-axis)} &: \begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} 1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\text{Reflect (about y-axis)} &: \begin{bmatrix} -1 & 0 \\ 0 & 1 \end{bmatrix} &\text{in 3D:} \begin{bmatrix} -1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\\\\
\end{align*} $$