# Linear Algebra - Matrices (Pt 5) - 
# In progress - Rank and non-square matrix explanation


## 1. Spans and spaces

- **Span**: The span of a set of vectors is **all linear combinations of those vectors**
- **Vector space** is denoted as $\mathbb{R}^n$. 
    - Every element in a vector space can be written as a **linear combination** of the elements in the **basis** (unit) vectors
        - **Basis (unit) vectors** (example): For a 2D vector space, the basis vectors are $\hat{i} = \left[\begin{smallmatrix} 1 \\ 0 \end{smallmatrix}\right]$ and $\hat{j} = \left[\begin{smallmatrix} 0 \\ 1 \end{smallmatrix}\right]$
        - A matrix $\textbf{A}$ applies a linear transformation to a vector space (i.e. all vectors in the space)
        - <mark>The columns of</mark> $\textbf{A}$ <mark>represent the **landing points** for the basis (unit) vectors **after the transformation**</mark>
            - By extension, $\textbf{A}$ moves **every input vector** (more precisely, the **point where every vector's tip is**) **linearly** to a new location.
        - We only need to know how $\textbf{A}$ transforms the bases $\hat{i}$ and $\hat{j}$, since
            - any other vector $\textbf{v}$ is <mark>just a **linear combination** of $\hat{i}$ and $\hat{j}$ **both before and after being transformed by $\textbf{A}$**</mark>
- **Subspace**: a subset of a larger vector space
    - <mark>**Geometric intuition**: A subspace of a 3D vector space is a 2D plane that passes through the origin</mark>
    - **Column space** (aka *range*, or *image*): Span (i.e. set of all possible linear combinations) of the column vectors of $\textbf{A}$
        - <mark>Geometrically:</mark> Essentially, the entire **output space**
    - **Row space**: Span of the row vectors of $\textbf{A}$
    - **Null space** (or **kernel**): If $\textbf{A} \cdot \textbf{x} = \textbf{0}$, the span of all solutions $\textbf{x}$ constitutes the **null space** of $\textbf{A}$
        - <mark>Geometrically:</mark> The space of all vectors that $\textbf{A}$ maps onto the zero vector (i.e. they are squished by $\textbf{A}$ onto the origin)
    - **Left-Null space**: If $\textbf{A}^\textrm{T} \cdot \textbf{x} = \textbf{0}$, the span of all solutions $\textbf{x}$ constitutes the **left-null space** of $\textbf{A}$
    
## 2. More properties

- **Rank**: The number of **linearly independent** columns (or rows) in $\textbf{A}$ is its rank
- **Orthonormal vectors**: Two unit length vectors whose inner (i.e. dot) products are 0 (e.g. $\hat{i}$ and $\hat{j}$)
- **Real value matrices**:
    - **Orthogonal matrices**: If $\textbf{A}$'s rows and cols are orthonormal vectors, $\textbf{A}$ is an orthogonal matrix. It satisfies:
        - $\textbf{A}^\textrm{T}\textbf{A} = \textbf{AA}^\textrm{T} = \textbf{I}$
    - **Symmetric matrix**: where $\textbf{A}^\textrm{T} = \textbf{A}$ (square matrices only) 
- **Complex value matrices**
    - Hermitian matrix: Complex matrices' analog to orthogonal matrix
    - Unitary matrix: Complex matrices' analog to symmetric matrix
- **Determinant**: This can be computed for any square matrix $\textbf{A}$
    - Matrices are only invertible if $det(\textbf{A}) \ne 0$. Such matrices are **non-singular**; and satisfy $\textbf{AA}^{-1}=\textbf{I}$
    - Matrices where $det(\textbf{A}) = 0$ are not invertible. They are **singular** matrices
  
## 3. Examples of the above (where relevant):

- The **span** of vectors $\left[\begin{smallmatrix} 1 \\ 0 \end{smallmatrix}\right]$ and $\left[\begin{smallmatrix} 0 \\ 1 \end{smallmatrix}\right]$ is the whole $x$-$y$ plane.
- A vector, $\textbf{v}$, with 3 elements is said to exist in **vector space** $\mathbb{R}^3$
- The $\mathbb{R}^3$ vector, $\textbf{v}$ is composed of (i.e. a linear combination of) the **basis vectors** $\hat{i} = \left[\begin{smallmatrix} 1 \\ 0 \\ 0 \end{smallmatrix}\right]$, $\hat{j} = \left[\begin{smallmatrix} 0 \\ 1 \\ 0 \end{smallmatrix}\right]$ and $\hat{k} = \left[\begin{smallmatrix} 0 \\ 0 \\ 1 \end{smallmatrix}\right]$.
- The subspace of a 3D vector (in $\mathbb{R}^3$) is the span of vectors $\left[\begin{smallmatrix} 1 \\ 0 \\ 0 \end{smallmatrix}\right]$, $\left[\begin{smallmatrix} 0 \\ 1 \\ 0 \end{smallmatrix}\right]$.
    - in this case the 2D $x$-$y$ plane is a subspace (subset) of the 3D $x, y, z$ vector space
- Vectors $\left[\begin{smallmatrix} 1 \\ 2 \\ 3 \end{smallmatrix}\right]$ and $\left[\begin{smallmatrix} 10 \\ 20 \\ 30 \end{smallmatrix}\right]$ are linearly dependent since one is a multiple of the other.
    - A matrix with those two vectors would be rank 1

# TODO: Kroenecker product, Tensors, Tensor products, 

https://en.wikipedia.org/wiki/Tensor
https://en.wikipedia.org/wiki/Tensor_product
https://en.wikipedia.org/wiki/Kronecker_product
https://en.wikipedia.org/wiki/Block_matrix
https://math.stackexchange.com/questions/973559/outer-product-of-two-matrices
https://stackoverflow.com/questions/24839481/python-matrix-outer-product


## 4. Back to Non-Square matrices (A <mark>geometric perspective</mark>)

A non-square matrix $\textbf{A} : \textbf{A} \in \mathbb{R}^{m\times n}$ has $m$ rows and $n$ columns. Geometrically, $\textbf{A}$ transforms a vector space $\mathbb{R}^n$ into a vector space $\mathbb{R}^m$. 

For example, the matrix $\textbf{A}$ transforms a 2D vector space into a 3D vector space. 
- Specifically, the **two** basis vectors (i.e. from 2D space) transform to 3D coordinates as follows: 

$$
\begin{align*}
\textbf{A} &= \begin{bmatrix} 3 & 1 \\ 4 & 1 \\ 5 & 9 \end{bmatrix}
\quad\quad\quad\quad\text{transforms: }
\hat{i}: \left[\begin{smallmatrix} 1 \\ 0 \end{smallmatrix}\right] \rightarrow \left[\begin{smallmatrix} 3 \\ 4 \\ 5 \end{smallmatrix}\right] \quad\text{and}\quad \hat{j}: \left[\begin{smallmatrix} 0 \\ 1 \end{smallmatrix}\right]\rightarrow \left[\begin{smallmatrix} 1 \\ 1 \\ 9 \end{smallmatrix}\right]
\end{align*}
$$

Similarly, matrix $\textbf{B}$ transforms a 3D vector space into a 2D vector space.
- Specifically, the **three** basis vectors (i.e. from 3D space) transform to 2D coordinates as follows:
$$
\begin{align*}
\textbf{B} &= \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
\quad\quad\quad\quad\text{transforms: }
\hat{i}: \left[\begin{smallmatrix} 1 \\ 0 \\ 0 \end{smallmatrix}\right] \rightarrow \left[\begin{smallmatrix} 1 \\ 4 \end{smallmatrix}\right]\text{,}\quad\quad\hat{j}: \left[\begin{smallmatrix} 0 \\ 1 \\ 0 \end{smallmatrix}\right] \rightarrow \left[\begin{smallmatrix} 2 \\ 5 \end{smallmatrix}\right]\quad\text{and}\quad\hat{k}: \left[\begin{smallmatrix} 0 \\ 0 \\ 1 \end{smallmatrix}\right] \rightarrow \left[\begin{smallmatrix} 3 \\ 6 \end{smallmatrix}\right]

\end{align*}
$$


### 4.1. Rank

- Definition: The **rank** of $\textbf{A} : \textbf{A} \in \mathbb{R}^{m\times n}$ is the **number of linearly independent columns or rows** in $\textbf{A}$
    - Rank is the **number of dimensions in the column-space** (aka. span of the column vectors of $\textbf{A}$ in $\mathbb{R}^m$ (or $\mathbb{R}^n$)).
    - Consequently, the number of linearly independent columns in a matrix $\equiv$ the number of linearly independent rows in that matrix.

#### 4.1.1. "Full Rank" Matrix

- $\textbf{A}$ is **full rank** if $\text{rank}(\textbf{A}) = \min(m,n)$ (i.e. the rank is as high as it can be)
- This is the same as:
    - if **all columns of $\textbf{A}$ are linearly independent**

#### 4.1.2. <mark>Geometric intuition for Rank:</mark>: 

- If matrix $\textbf{A}$ is a transformation, the <mark>rank is the **number of dimensions in the output space**</mark>. Examples: 
    - If some matrix $\textbf{A}$ transformed some arbitrary vector space $\mathbb{R}^n$ into a <mark>1D line</mark> in $\mathbb{R}^1$, then $\text{rank}(\textbf{A}) = 1$
    - If $\textbf{A}$ transformed some vector space $\mathbb{R}^n$ to a <mark>2D plane</mark> in $\mathbb{R}^2$, then $\text{rank}(\textbf{A}) = 2$
- In general, if $\textbf{A}$ transforms some vector space $\mathbb{R}^n$ to $\mathbb{R}^m$, then $\text{rank}(\textbf{A}) = m$

#### 4.1.3. <mark>Geometric intuition, examples</mark>:
- A $2\times 2$ matrix is full rank (i.e. rank 2) if the output is a 2D space ($\mathbb{R}^2$; same as the input space). $\text{det}(\textbf{A}) \neq 0$
- A $3\times 3$ matrix is full rank (i.e. rank 3) if the output is a 3D space ($\mathbb{R}^3$; same as the input space). $\text{det}(\textbf{A}) \neq 0$. However,
    - If the $3\times 3$ matrix collapsed the input space to a 2D plane, then it is only rank 2 (NB: **but it can collapse further**)
    - If the $3\times 3$ matrix collapsed the input space to a 1D line, then it is only rank 1
- A $2\times 3$ matrix is full rank (i.e. rank 2) if the output is a 2D plane in $\mathbb{R}^3$ (same as the input space)

#### 2.1.4. Augmented Matrix

- If vector $\textbf{y}$ is concatenated to matrix $\textbf{A}$, we say "$\textbf{A}$ augmented with $\textbf{y}$". Denoted as $(\textbf{A}\vert \textbf{B})$.
    - if $\text{rank}((\textbf{A}\vert \textbf{B})) = \text{rank}(\textbf{A})+1$, then vector $\textbf{y}$ is **"new" information**
    - otherwise, if $\text{rank}((\textbf{A}\vert \textbf{B})) = \text{rank}(\textbf{A})$,  it means $\textbf{y}$ can be created as a linear combination of the columns in $\textbf{A}$

In [5]:
# Compute the condition number and rank for matrix A = [[1,1,0],[0,1,0],[1,0,1]]
# If y = [[1],[2],[1]], get the augmented matrix [A,y]

from numpy import trace
from numpy.linalg import cond, matrix_rank

A = np.array([[1, 1, 0], [0, 1, 0], [1, 0, 1]])
y = np.array([[1], [2], [1]])
print("A matrix's shape:", A.shape, "\ny vector's shape", y.shape)

print("\nCondition number(A):", cond(A))
print("Rank(A):", matrix_rank(A))
print("Trace(A):", trace(A))

A_y = np.concatenate((A, y), axis=1)
print("\nOriginal A matrix:\n", A, "\ny vector:\n", y, "\n\nAugmented (A|y) matrix:\n", A_y)
print("Rank(A_y):", matrix_rank(A_y))

print("\nNote that the rank of A and A_y are both 3, so y is a linear combination of the columns of A.")
print("Therefore, there is no new information in y that is not already in A.")


A matrix's shape: (3, 3) 
y vector's shape (3, 1)

Condition number(A): 4.048917339522305
Rank(A): 3
Trace(A): 3

Original A matrix:
 [[1 1 0]
 [0 1 0]
 [1 0 1]] 
y vector:
 [[1]
 [2]
 [1]] 

Augmented (A|y) matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]
Rank(A_y): 3

Note that the rank of A and A_y are both 3, so y is a linear combination of the columns of A.
Therefore, there is no new information in y that is not already in A.
