## 1. Recap: A few ways to multiply vectors and matrices

### 1.1. Vector multiplication operations (4 approaches)

Given we have 2 vectors, $\textbf{a}$ and $\textbf{b}$, of same length (i.e. $\textbf{a}, \textbf{b}\in\mathbb{R}^{n}$,), we can "multiply" them in the following ways:

1. Vector dot (inner) product: $\textbf{a} \cdot \textbf{b} = \textbf{a}^T\textbf{b} = \Sigma_{i=1}^n a_i b_i = \Vert\textbf{a}\Vert\:\Vert\textbf{b}\Vert \cos \theta$
2. Vector outer product: $\textbf{a} \otimes \textbf{b} = \textbf{a} \textbf{b}^T$. The resultant matrix is of size $n \times n$ and its elements are given by: $ (\textbf{a} \otimes \textbf{b})_{ij} = a_i b_j$
3. Vector Hadamard (aka element-wise) product: $\textbf{a}\odot \textbf{b}$. Elements of the resultant vector are given by: $ (\textbf{a}\odot \textbf{b})_{i} = (\textbf{a})_{i}(\textbf{b})_{i} $
4. Vector cross product: $\textbf{a} \times \textbf{b} = \Vert \textbf{a} \Vert \: \Vert \textbf{b} \Vert\sin{(\theta)} \, \textbf{n}$

### 1.2. Matrix multiplication operations (4 approaches)

Given we have a matrix, $\textbf{A}:\textbf{A}\in\mathbb{R}^{m \times n}$, following are a few multiplication operations involving $\textbf{A}$. <mark>**NB: inner dimensions must match!**</mark>
1. Matrix $\textbf{A}$ and some vector (examples: column vector $\textbf{v}$, and row vector $\textbf{w}^\textrm{T}$):
   1. Matrix times vector: $\textbf{Av}$, where vector $\textbf{v}\in\mathbb{R}^{n \times 1}$. Hence, resultant column vector $\textbf{Av}\in\mathbb{R}^{m \times 1}$
   2. Vector times matrix: $\textbf{w}^\textrm{T}\textbf{A}$, where vector $\textbf{w}^\textrm{T}\in\mathbb{R}^{1 \times m}$. Hence, resultant row vector $\textbf{w}^\textrm{T}\textbf{A}\in\mathbb{R}^{1 \times n}$
2. Matrix $\textbf{A}$ and some matrix (examples: $\textbf{A}$ and $\textbf{B}$ matrices are of same size, but $\textbf{C}$ matrix has different size):
   1. Matrix Hadamard (aka element-wise) product: $\textbf{A}\odot \textbf{B}$, where $\textbf{A},\textbf{B}\in\mathbb{R}^{m \times n}$. Elements of the resultant matrix are given by: $ (A\odot B)_{ij} = (A)_{ij}(B)_{ij} $
   2. Matrix multiplication: $\textbf{AC}$, where $\textbf{A}\in\mathbb{R}^{m \times p}$ and $\textbf{C}\in\mathbb{R}^{p \times n}$. Hence, inner dimensions match, and resultant matrix $\textbf{AC}\in\mathbb{R}^{m \times n}$
      


In [1]:
import numpy as np  # more basic functionality
import scipy  # advanced functionality, built on numpy

# Find the inner and outer products of two 1D arrays (not exactly vectors, no double [[]])
a = np.array([4, 5, 6])
b = np.array([7, 8, 9])

print("Given vectors a:", a, "and b:", b)

print("\n4 types of vector multiplication")
print(
    "- Inner (aka dot) product: a•b = (a^T)b =", np.inner(a, b)
)  # dot prod; dims are: [1x3][3x1]=[1x1] <-- output dim, scalar
print("- Hadamard (elementwise) product: a⊙b", a * b)  # elementwise (or hadamard) product
print("- Cross product, a⨉b:", np.cross(a, b))
print("- Outer product, a[3⨉1] ⨂ b[1⨉3]:\n", np.outer(a, b))  # dims are [3x1][1x3]=[3x3] <-- output dim


Given vectors a: [4 5 6] and b: [7 8 9]

4 types of vector multiplication
- Inner (aka dot) product: a•b = (a^T)b = 122
- Hadamard (elementwise) product: a⊙b [28 40 54]
- Cross product, a⨉b: [-3  6 -3]
- Outer product, a[3⨉1] ⨂ b[1⨉3]:
 [[28 32 36]
 [35 40 45]
 [42 48 54]]


## 3. Gram-Schmidt Process

Use this to orthonormalise anything (vector or matrix (orthogonalise))

- Orthonormalise a set of vectors $\{\textbf{v}_1, \textbf{v}_2, \textbf{v}_3, ..., \textbf{v}_n\}$ 
    - to $\{\textbf{u}_1, \textbf{u}_2, \textbf{u}_3, ..., \textbf{u}_n\}$, where each $\textbf{u}_i$ vector is in the same $\mathbb{R}^n$ vector space, 
        - but each $\textbf{u}_i$ vector is unit length, and 
        - is mutually orthogonal with other vectors

I.e. Transform a set of vectors into a set of orthonormal vectors in the same vector space

## 4. Matrix decompositions

### 4.1. Gaussian Elimination (or Decomposition?)

- **Purpose**: We use Gaussian Elimination to simplify a system of linear equations, $\textbf{Ax=b}$ into *row echelon form* (or *reduced row echelon form*; which allows solving $\textbf{Ax=b}$ by simple inspection)
- Application: 
    - Solving linear system $\textbf{Ax=b}$, 
    - Computing inverse matrices
    - Computing rank
    - Computing determinant
    - **Elementary row operations**: Methods by which the above are done
        - Swapping rows
        - Scaling rows
        - Adding rows to each other (i.e. creating linear combinations)
        
- **Row echelon form**: The first *non-zero* element from the left in each row (aka leading coefficient, pivot) is **always to the right of** the first *non-zero* element in the row above
- **Reduced row echelon form**: Row echelon form whose pivots are $1$ and column containing pivots are $0$ elsewhere

- Elementary row operation

### 4.2. LU Decomposition

Like Gaussian Decomposition, but more computationally efficient

Decompose any matrix $\textbf{A}$ (square or not) into:
- A lower triangular matrix $\textbf{L}$
- An upper triangular matrix $\textbf{U}$
- Sometimes needing to reorder $\textbf{A}$ using a $\textbf{P}$ matrix

In [2]:
a = np.random.randn(3, 4)
print("A:\n", a)

p, l, u = scipy.linalg.lu(a)
print("\nP:\n", p)
print("\nL:\n", l)
print("\nU:\n", u)
print("\n----\n\nRecomposition: PLU = A:\n", p @ l @ u)


A:
 [[-1.42490189 -0.91221588 -1.93062968 -0.36094733]
 [-0.53549468 -0.13589574  0.47988497  2.88155355]
 [-0.00873341  1.07556415  1.3429852  -0.12939715]]

P:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

L:
 [[1.         0.         0.        ]
 [0.00612913 1.         0.        ]
 [0.37581162 0.19139304 1.        ]]

U:
 [[-1.42490189 -0.91221588 -1.93062968 -0.36094733]
 [ 0.          1.08115524  1.35481827 -0.12718486]
 [ 0.          0.          0.94613525  3.04154405]]

----

Recomposition: PLU = A:
 [[-1.42490189 -0.91221588 -1.93062968 -0.36094733]
 [-0.53549468 -0.13589574  0.47988497  2.88155355]
 [-0.00873341  1.07556415  1.3429852  -0.12939715]]


### 4.3. QR Decomposition

Decompose a matrix $\textbf{A}$ into:
- an orthogonal matrix $\textbf{Q}$
- an upper triangular matrix $\textbf{R}$

It's used in QR algorithms to solve the linear least square problem. 

Also, the $\textbf{Q}$ matrix is sometimes what we desire after the **Gram-Schmidt process**

In [3]:
a = np.random.randn(3, 4)
print("A:\n", a)

q, r = np.linalg.qr(a)
print("\nQ:\n", q)
print("\nR:\n", r)
print("\n----\n\nRecomposition: QR = A:\n", q @ r)


A:
 [[ 0.1896593   0.18586154 -1.09719411  1.42682447]
 [-0.76706589  1.29836654  0.61490277  0.26874477]
 [-0.82562671 -0.88687333 -0.79760309  0.90900003]]

Q:
 [[-0.16595838 -0.13945844  0.97622188]
 [ 0.67120893 -0.74122266  0.0082184 ]
 [ 0.72245166  0.65661275  0.21661787]]

R:
 [[-1.1428124   0.19990683  0.01858711  0.60029899]
 [ 0.         -1.57063101 -0.82648325  0.19867857]
 [ 0.          0.         -1.23882645  1.59201156]]

----

Recomposition: QR = A:
 [[ 0.1896593   0.18586154 -1.09719411  1.42682447]
 [-0.76706589  1.29836654  0.61490277  0.26874477]
 [-0.82562671 -0.88687333 -0.79760309  0.90900003]]


### 4.4. Cholesky Decomposition

Decompose a symmetric (or Hermitian) positive-definite matrix into:

- a lower triangular matrix $\textbf{L}$
- and its transpose (or conjugate transpose) $\textbf{L.H.}$

Used in algorithms for numerical convenience

In [4]:
x = np.diagflat([[1, 2], [3, 4]])
print("x:\n", x)

L = np.linalg.cholesky(x)
print("\nL:\n", L)

print("\n----\n\nRecomposition: LL^T:\n", L @ L.T)


x:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

L:
 [[1.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.        ]
 [0.         0.         1.73205081 0.        ]
 [0.         0.         0.         2.        ]]

----

Recomposition: LL^T:
 [[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


# Questions

- When exactly do we use decompositions?