In [1]:
import numpy as np # more basic functionality
import scipy # advanced functionality, built on numpy
import matplotlib as mpl
import matplotlib.pyplot as plt

# Summary

- Eigenvalues and Eigenvectors
    - Eigenvectors are the vectors that does not change its orientation when multiplied by the transition matrix, but it just scales by a factor of corresponding eigenvalues.
- Diagonalization & Eigendecomposition
    - A few applications of eigenvalues and eigenvectors that are very useful when handing the data in a matrix form because you could decompose them into matrices that are easy to manipulate.
- Underlying assumption behind the diagonalization and eigendecomposition
    - Make sure that the matrix you are trying to decompose is a square matrix and has linearly independent eigenvectors (different eigenvalues).

## More terminology:

### Spans and spaces

- **Span**: The span of a set of vectors is all linear combinations of those vectors
- **Vector space** is denoted as $\mathbb{R}^n$. 
    - Every element in a vector space can be written as a **linear combination** of the elements in the **basis** (unit) vectors
        - **Basis (unit) vectors** (example): For a 2D vector space, the basis vectors are $\hat{i} = \begin{bsmallmatrix} 1 \\ 0 \end{bsmallmatrix}$ and $\hat{j} = \begin{bsmallmatrix} 0 \\ 1 \end{bsmallmatrix}$
        - A matrix $A$ applies a linear transformation to a vector space (i.e. all vectors in the space)
        - <mark>The columns of $A$ represent the **landing points** for the basis (unit) vectors **after the transformation**</mark>
        - By extension, $A$ moves **every input vector** (more precisely, the **point where every vector's tip is**) **linearly** to a new location.
        - We only need to know how $A$ transforms the bases $\hat{i}$ and $\hat{j}$, since
            - any vector $v$ is <mark>just a **linear combination** of $\hat{i}$ and $\hat{j}$ **both before and after being transformed by $A$**</mark>
- **Subspace**: a subset of a larger vector space
    - **Column space**: Span of all column vectors of of matrix $A$
    - **Row space**: Span of all row vectors of matrix $A$
    - **Null space**: If $A \cdot x = 0$, the span of all solutions $x$ constitutes the **null space** of $A$
    - **Left-Null space**: If $A^T \cdot x = 0$, the span of all solutions $x$ constitutes the **left-null space** of $A$
    
### More properties

- **Rank**: The number of **linearly independent** columns (or rows) in $A$ is its rank
- **Orthonormal vectors**: Two unit length vectors whose inner (i.e. dot) products are 0
- **Real value matrices**:
    - **Orthogonal matrices**: If $A$'s rows and cols are orthonormal vectors, $A$ is an orthogonal matrix. It satisfies:
        - $A^TA = AA^T = I$
    - **Symmetric matrix**: where $A^T = A$ (square matrices only) 
- **Complex value matrices**
    - Hermitian matrix: Complex matrices' analog to orthogonal matrix
    - Unitary matrix: Complex matrices' analog to symmetric matrix
- **Determinant**: This can be computed for any square matrix $A$
    - Matrices are only invertible if $det(A) \ne 0$. Such matrices are **non-singular**; and satisfy $AA^{-1}=I$
    - Matrices where $det(A) = 0$ are not invertible. They are **singular** matrices
  
#### Examples of the above (where relevant):

- The **span** of vectors (0,1) and (1,0) is the whole x-y plane
- A vector, $v$, with 3 elements is said to exist in **vector space** $\mathbb{R}^3$
- The $\mathbb{R}^3$ vector, $v$ is composed of **basis vectors** (1,0,0), (0,1,0), and (0,0,1).
- The subspace of a 3D vector (in $\mathbb{R}^3$) is the span of vectors (1,0,0) and (0,1,0) 
    - in this case the 2D x-y plane is a subspace (subset) of the 3D x,y,z vector space
- Vectors (1,2,3) and (10,20,30) are linearly dependent since one is a multiple of the other.
    - A matrix with those two vectors would be rank 1

### Recap: A few ways to multiply vectors

In [2]:
# Find the inner and outer products of two 1D arrays (not exactly vectors, no double [[]])
a = np.array([4,5,6])
b = np.array([7,8,9])

print('Types of vector multiplication')
print('inner:', np.inner(a,b)) # dot prod; dims are: [1x3][3x1]=[1x1] <-- output dim
print('outer:', np.outer(a,b)) # dims are [3x1][1x3]=[3x3] <-- output dim
print('hadamard:', a * b) # elementwise (or hadamard) product

Types of vector multiplication
inner: 122
outer: [[28 32 36]
 [35 40 45]
 [42 48 54]]
hadamard: [28 40 54]


### Gram-Schmidt Process

Use this to orthonormalise anything (vector or matrix (orthogonalise))

- Orthonormalise a set of vectors $\{\bar{v_1}, \bar{v_2}, \bar{v_3}, ..., \bar{v_n}\}$ 
    - to $\{\bar{u_1}, \bar{u_2}, \bar{u_3}, ..., \bar{u_n}\}$, where each $u$ vector is in the same $\mathbb{R}^n$ vector space, 
        - but each vector is unit length, and 
        - is mutually orthogonal with other vectors

I.e. Transform a set of vectors into a set of orthonormal vectors in the same vector space

## Matrix decompositions

### Gaussian Elimination (or Decomposition?)

- **Purpose**: We use Gaussian Elimination to simplify a system of linear equations, $Ax=b$ into *row echelon form* (or *reduced row echelon form*; which allows solving $Ax=b$ by simple inspection)
- Application: 
    - Solving linear system $Ax=b$, 
    - Computing inverse matrices
    - Computing rank
    - Computing determinant
    - **Elementary row operations**: Methods by which the above are done
        - Swapping rows
        - Scaling rows
        - Adding rows to each other (i.e. creating linear combinations)
        
- **Row echelon form**: The first *non-zero* element from the left in each row (aka leading coefficient, pivot) is **always to the right of** the first *non-zero* element in the row above
- **Reduced row echelon form**: Row echelon form whose pivots are $1$ and column containing pivots are $0$ elsewhere

- Elementary row operation

### LU Decomposition

Like Gaussian Decomposition, but more computationally efficient

Decompose any matrix $A$ (square or not) into:
- A lower triangular matrix $L$
- An upper triangular matrix $U$
- Sometimes needing to reorder $A$ using a $P$ matrix

In [3]:
a = np.random.randn(3,4)
print('A:\n', a)

p,l,u = scipy.linalg.lu(a)
print('\nP:\n', p)
print('\nL:\n', l)
print('\nU:\n', u)
print('\n----\n\nRecomposition: PLU = A:\n', p@l@u)

A:
 [[-0.55038208 -1.64274921  0.74248386  1.05567946]
 [-0.37105223  1.64296612 -0.9953272   1.42100597]
 [-0.88663242  1.07443251  1.56042151  0.51827791]]

P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

L:
 [[ 1.          0.          0.        ]
 [ 0.62075565  1.          0.        ]
 [ 0.41849612 -0.51665389  1.        ]]

U:
 [[-0.88663242  1.07443251  1.56042151  0.51827791]
 [ 0.         -2.30970927 -0.22615661  0.73395552]
 [ 0.          0.         -1.76520225  1.58330965]]

----

Recomposition: PLU = A:
 [[-0.55038208 -1.64274921  0.74248386  1.05567946]
 [-0.37105223  1.64296612 -0.9953272   1.42100597]
 [-0.88663242  1.07443251  1.56042151  0.51827791]]


### QR Decomposition

Decompose a matrix $A$ into:
- an orthogonal matrix $Q$
- an upper triangular matrix $R$

It's used in QR algorithms to solve the linear least square problem. 

Also, the $Q$ matrix is sometimes what we desire after the **Gram-Schmidt process**

In [4]:
a = np.random.randn(3,4)
print('A:\n', a)

q,r = np.linalg.qr(a)
print('\nQ:\n', q)
print('\nR:\n', r)
print('\n----\n\nRecomposition: QR = A:\n', q@r)

A:
 [[-1.33656849  0.47121422  0.84715639 -1.63111615]
 [ 1.0110986   0.73512738 -0.23842762  0.01694656]
 [-0.4905946  -0.94730809  0.71554459  0.96648081]]

Q:
 [[-0.76538983 -0.58201376  0.27466052]
 [ 0.57900855 -0.43644523  0.68866876]
 [-0.28094042  0.68613086  0.67104167]]

R:
 [[ 1.74625851  0.33111959 -0.98748191  0.98672838]
 [ 0.         -1.2450733   0.10196114  1.6050681 ]
 [ 0.          0.          0.548643    0.21221625]]

----

Recomposition: QR = A:
 [[-1.33656849  0.47121422  0.84715639 -1.63111615]
 [ 1.0110986   0.73512738 -0.23842762  0.01694656]
 [-0.4905946  -0.94730809  0.71554459  0.96648081]]


### Cholesky Decomposition

Decompose a symmetric (or Hermitian) positive-definite matrix into:

- a lower triangular matrix $L$
- and its transpose (or conjugate transpose) $L.H.$

Used in algorithms for numerical convenience

In [5]:
x = np.diagflat([[1,2], [3,4]])
print('x:\n', x)

L = np.linalg.cholesky(x)
print('\nL:\n', L)

print('\n----\n\nRecomposition: LL^T:\n', L @ L.T)

x:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

L:
 [[1.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.        ]
 [0.         0.         1.73205081 0.        ]
 [0.         0.         0.         2.        ]]

----

Recomposition: LL^T:
 [[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


## Eigenvalue Problem and the Characteristic Polynomial

A non-zero vector $v$ of dim. $\mathbb{R}^n$ is an **eigenvector of square matrix $A : A\in \mathbb{R}^{n\times n}$** 
- if it satisfies a linear equation of the form: $Av = \lambda v$; for some scalar $\lambda$ <mark>which we are solving for</mark>
    - This is called the eigenvalue equation/problem
    - **Geometric intuition**: The eigenvector(s) of $A$ are the vector(s) ($v$) which $A$ **only elongates/shrinks**, and never takes off it's span(s). 
        - The amount of this elongation/shrink is $\lambda$, a scalar value
- Rearranging the eigenvalue problem:

$$ \begin{align*}
Av&=\lambda v\\ 
Av&=(\lambda I) v = \begin{bsmallmatrix} 
                    \lambda & 0 & \dots & 0 \\ 
                    0 & \lambda & \dots & 0 \\ 
                    \vdots & \vdots & \ddots & \vdots \\ 
                    0 & 0 & \dots & \lambda \\ 
                    \end{bsmallmatrix} \begin{bsmallmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bsmallmatrix}\\
(A-\lambda I) v &= 0\\
\end{align*} $$

$\text{Since }v \ne 0\text{, solve for:}$

$$ \begin{align*}
p(\lambda) = \text{det}(A-\lambda I)&=0\\
\end{align*} $$



- <mark>The **only way for $(A-\lambda I) v = 0$ to be possible** (given non-zero $v$) is for $\text{det}(A-\lambda I)=0$</mark>
    - i.e. The matrix $(A-\lambda I$) represents a *linear transform. of the vector space which "reduces" its dimensionality* (at least 1 dim is lost)
    - A matrix **cannot squish non-zero vectors into the $\vec{0}$ vector, except when their determinant is 0**
- By computing the determinant, we get the eigenvalues $\lambda_1, \lambda_2(, ..., \lambda_n)$ (1 for each dimension of the square matrix).
    - Computing $\text{det}(A-\lambda I)$ requires solving a **characteristic polynomial** whose roots are the $\lambda$(s)
 
#### Why the $\text{det}(A-\lambda I) = 0$ observation matters
- The observation that $\text{det}(A-\lambda I)\equiv 0$ is only useful because solving it yields the eigenvalues $\lambda$s.
    - Those helps us solve for the eigenvectors $v$s (i.e. those vectors that this diagonally altered matrix $(A-\lambda I)$ "shrinks" to 0)

In [10]:
# A = np.random.randn(4,4)
A = np.array([[3,1],
             [0,2]])
print('A:\n', A)
lambdas,v = np.linalg.eig(A)

print('Eigenvalues):\n', lambdas)
print('Eigenvectors:\n', v)

A:
 [[3 1]
 [0 2]]
Eigenvalues):
 [3. 2.]
Eigenvectors:
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


## Eigenbasis, Diagonalisation, and Eigen-decomposition

## Eigenbasis
- If our <mark>**basis vectors** ($\hat{i} = \begin{bsmallmatrix} 1 \\ 0 \end{bsmallmatrix}\\, \hat{j} = \begin{bsmallmatrix} 0 \\ 1 \end{bsmallmatrix}\\, \dots$) are themselves **eigenvectors**</mark>. It is called an eigenbasis then if we inspect $A$, the transformation matrix, it will have the form known as a <mark>**Diagonal Matrix**</mark>:
$$A = \begin{bsmallmatrix} \lambda_1 & 0 \\ 0 & \lambda_2 \end{bsmallmatrix}$$
- Its form is <mark>(diagonal) because recall $A$ **only scales** (stretch/shrink) its eigenvectors</mark>, which in this case are the basis vectors
    - It is very easy to compute large powers of diagonal matrices (they simply scale vectors by the eigenvalues)
 
## <mark>Diagonalisation</mark>: Using the Eigenbasis to Diagonalise any non-diagonal $A$
1. Find the eigenvectors of $A$
2. Make a **change of basis** matrix $S$ whose columns are the eigenvectors of $A$. We'll use this to switch the coordinate system of $A$
3. Diagonalise $A$ to get $\Lambda$ by doing this:
$$\Lambda = S^{-1}AS$$
4. The new matrix $\Lambda$ is guaranteed to be diagonal, with its **eigenvalues on the main diagonal**

#### Why is diagonalisation $\Lambda = S^{-1}AS$ possible in the first place?

Show that $AS=S\Lambda$
- Suppose we have $m$ linearly independent eigenvectors of $A$;
    - then $S$ is a matrix, where each column is an eigenvector of $A$, $v_{1\dots m}$
    - $AS = A \begin{bsmallmatrix} v_1 & v_2 & \dots & v_m \end{bsmallmatrix} = \begin{bsmallmatrix} A v_1 & A v_2 & \dots & A v_m \end{bsmallmatrix} = \begin{bsmallmatrix} \lambda_1 v_1 & \lambda_2 v_2 & \dots & \lambda_m v_m \end{bsmallmatrix} $ (final step because recall $Av=\lambda $)
- And so $\begin{bsmallmatrix} \lambda_1 v_1 & \lambda_2 v_2 & \dots & \lambda_m v_m \end{bsmallmatrix}$ = $\begin{bsmallmatrix} \ v_1 & \ v_2 & \dots & \ v_m \end{bsmallmatrix} \begin{bsmallmatrix} 
\ \lambda_1 & 0 & \dots & 0 \\
\ 0 & \lambda_2 & \dots & 0 \\
\ \vdots & \vdots & \ddots & \vdots \\
\ 0 & 0 & \dots & \lambda_m \\
\end{bsmallmatrix} $ which is $S\Lambda$

#### Assumptions:

The matrix $A$ you are trying to decompose must:
- be a square matrix
- have linearly independent eigenvectors (different eigenvalues, 1 for each row of the matrix)

## Now that we know $AS=S\Lambda$, we can do:

### Diagonalisation:

- <mark>Takes $A$ matrix to produce $\Lambda$, a diagonal matrix with **eigenvalues on the main diagonal**</mark>
- Multiply both sides by $S^{-1}$ **from the left**. 

$$
\begin{align*}
S^{-1}\times AS &= S^{-1}\times S\Lambda \\
S^{-1}AS &= S^{-1}S\Lambda \\
S^{-1}AS &= \Lambda \\ \\
\Lambda &= S^{-1}AS
\end{align*}
$$

### Eigendecomposition

- After diagonalising $A$ to get $\Lambda$, <mark>we can use eigendecomposition to do quick matrix multiplications of A</mark>
- Multiply both sides by $S^{-1}$ **from the right**

$$
\begin{align*}
AS \times S^{-1} &= S\Lambda \times S^{-1} \\
ASS^{-1} &= S\Lambda S^{-1} \\
A &= S\Lambda S^{-1}
\end{align*}
$$

$\text{Now note, if we raise $A$ to arbitrary powers}$

$$
\begin{align*}
A^2 &= (S\Lambda S^{-1})(S\Lambda S^{-1}) \\
&= S\Lambda (S^{-1}S)\Lambda S^{-1} = S\Lambda^2 S^{-1}\\\\
\text{In general } A^k &= S\Lambda^k S^{-1}
\end{align*}
$$

# Questions

- When exactly do we use decompositions?
- What is the intuition behind an eigenvalue and eigenvector?
- Some interesting edge cases (what are the eigenvalues and eigenvectors for):
    - A rotation-only matrix like $\begin{bsmallmatrix} 0 & -1 \\ 1 & 0 \end{bsmallmatrix}$ has only imaginary $\lambda=i$. No eigenvectors, as each vector is rotated
    - A shear matrix like $\begin{bsmallmatrix} 1 & 1 \\ 0 & 1 \end{bsmallmatrix}$: only 1 eigenvalue ($\lambda = 1$), so only 1 eigenvector (all vectors on the x-axis are eigenvectors)
    - A scaling-only matrix like $\begin{bsmallmatrix} 2 & 0 \\ 0 & 2 \end{bsmallmatrix}$: only 1 eigenvalue ($\lambda = 2$), but **all** vectors in the plane are eigenvectors, and scaled by 2x