# Objects in Linear Algebra

Commonly encountered objects and calculations in Linear Algebra, implemented in Python.

Sources:
- [Python Numerical Methods: Basics of Linear Algebra](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter14.01-Basics-of-Linear-Algebra.html)

## Key Takeaways:

### Syntax 

- To define vectors and matrices in NumPy, use `np.array([[]])` with double square brackets
    - A row vector: `[[ csv row elements ]]`
    - A column vector: `[[elem 1], [elem 2], elem 3]]`, and you can put each on a new line
    - A matrix: ``[[ csv row 1], [ csv row 2], ...]``, and you can put each on a new line

### Concepts covered
- Basics set notation
- Vectors 
    - Definition and properties (transpose, length `norm`s)
    - Addition
    - Multiplication (scalar, dot, and cross product)
    - Angle between 2 vectors (via dot product)
- Matrices
    - Definition and properties (transpose, length `norm`s)
    - Addition and scalar multiplication
    - Matrix multiplication (using `np.dot`) - inner dimensions must match
        - *NB: A vector is just a matrix with 1 column (or row if it's a row vector)*
    - Square matrices
        - **Determinant**
        - May be **invertible** (if $AA^{-1}=I)$:
            - **Singular** (non-invertible) matrix if $det(A) = 0$
                - Ill-conditioned if determinant is *close to 0* (**high** condition number = **more** singular)
            - **Non-singular** (invertible) matrix if $det(A) \ne 0$
        - **Rank**: the number of linearly independent columns in the matrix)
        - **Trace**: the sum of on-diagonal elements
        - Identity Matrix
        - Augmented matrix (concatenating a vector $y$ to a matrix $A$ to give $[A,y]$)


## List of functions left to write

- Masks (e.g. lower triangle, upper triangle and identity)
- Basic identities (e.g. LU decomposition and the other commonly used ones, $Z^TZ$ etc, $A^TAI$)

In [1]:
import numpy as np # more basic functionality
import scipy # advanced functionality, built on numpy
import matplotlib as mpl
import matplotlib.pyplot as plt

## Set Notation

- A collection of objects (objects are denoted in braces {})
    - **empty set** (denoted $\{\}$ or $\emptyset$): the set containing no objects)
- **Union**: Set containing all elements of $A$ and $B$ is denoted: $A \cup B$
- **Intersect**: Set containing alalements that belong to **both** $A$ *and* $B$ is denoted: $A \cap B$
- Colon ($:$) means "**such that**"
- $a\in A$ means "element $a$ is a member of set $A$"
- Backslash ($\backslash$) means ""**set minus**" so if $a\in A$, then  $A\backslash a$ means "$A$ minus the element $a$"
- Some standard sets related to numbers: 
    - Naturals: $\mathbb{N} = \{1, 2, 3, 4, \cdots\}$
    - Wholes: $\mathbb{W} = \mathbb{N} \cup \{0\}$
    - Integers: $\mathbb{Z} = \mathbb{W} \cup \{-1, -2, -3, \cdots\}$
    - Rationals: $\mathbb{Q} =  \{\frac{p}{q} : p\in {\mathbb{Z}}, q\in {\mathbb{Z}} \backslash \{0\}\}$
    - Irrationals: $\mathbb{I}$ is the set of real numbers not expressible as a fraction of integers
    - Reals: $\mathbb{R} = \mathbb{Q} \cup \mathbb{I}$
    - Complex numbers: $\mathbb{C} = \{a + bi : a,b\in {\mathbb{R}}, i = \sqrt{-1}\}$
- Example:
    - Let $S$ be the set of all real $(x,y)$ pairs such that $x^2 + y^2 = 1$ Write $S$ using set notation:
    - $S = \{(x,y) : x,y \in {\mathbb{R}}, x^2 + y^2 = 1\}$





## Vectors

### Properties of a vector $v$:
- $i$'th element: $v_i$
- Transpose (turns columns into rows and vice versa): $v^T$ (for a matrix it swaps rows with columns)
- Length (many definitions (distance formulas) we can use):
    - $L_2$ norm (Euclidian length): $||v||_2 = \sqrt{\Sigma_i v_{i}^{2}}\quad$ (*physical length* of a vector in n-dim space)
    - $L_1$ norm (Manhattan Distance): $||v||_1 = \Sigma_i |v_i|\quad $
    - More generally, 
        - The **p-norm** is $\Vert v \Vert_{p} = \sqrt[p]{(\sum_i v_i^p)}$
        - And the $L_\infty$ norm, $||v||_\infty$, is the $p$-norm where $p=\infty$

In [2]:
# Create a row vector and a column vector, show their shapes

row_vec = np.array([[1, -5, 3, 2, 4]])
col_vec = np.array([[1],
                    [2],
                    [3],
                    [4]])

# Comments show output if you don't use list of lists
print(row_vec) # [ 1 -5  3  2  4]
print(col_vec) # [1 2 3 4]
print(row_vec.shape) # (5,)
print(col_vec.shape) # (4,)

[[ 1 -5  3  2  4]]
[[1]
 [2]
 [3]
 [4]]
(1, 5)
(4, 1)


In [3]:
# Transpose row_vec and calculate L1, L2, and L_inf norms
from numpy.linalg import norm

transposed_row_vec = row_vec.T
print(transposed_row_vec)

norm_1 = norm(transposed_row_vec, 1)
norm_2 = norm(transposed_row_vec, 2) # <- L2 norm is default and most common
norm_inf = norm(transposed_row_vec, np.inf)

print('L_1 is: %.1f' % norm_1)
print('L_2 is: %.1f' % norm_2)
print('L_inf is: %.1f' % norm_inf) # NB: norm_inf = |largest element|

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


## Vector addition

Elementwise addition; if vectors are of of same length (i.e. if $v$ and $w$ are both in $\mathbb{R}^n$) then:

- By vector addition, $u = v + w$ is the vector with $u_i = v_i + w_i$


In [4]:
# Sum vectors v = [10, 9, 3] and w = [2, 5, 12]
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
u = v + w
print(u)

[[12 14 15]]


## Multiplying vectors

### Scalar multiplication

To multiply a vector $v$, by a scalar $\alpha$ (a number in $\mathbb{R}$), do it "elementwise" or "pairwise".

- By scalar multiplication of a vector $u = \alpha v$ is the vector with $u_i = \alpha v_i$


### Vector multiplication

#### Vector dot product

Geometric interpretation: <mark>A measure of how similarly directed two vectors are</mark>

It's the sum of elementwise products. For $v, w \in \mathbb{R}^n$, 

- The dot product is: $d = v \cdot w = \Sigma_{i=1}^n v_i w_i$
- Note also, since $v, w \in \mathbb{R}^n$, transpose to make inner dimensions match. Dot product can hence be rewritten as:
    - $d = \bar{v} \cdot \bar{w} = v^Tw$

##### Angle between vectors

Extending on the dot product idea, $v \cdot w$, the **angle between two vectors** $\theta$. It is as defined by the formula:

- Think of dot product as "**degree of alignment**": $v \cdot w = ||v||_2||w||_2 \cos \theta$
    - (1,1) and (2,2) are **parallel**; computing the angle gives $\theta = 0$
    - (1,1) and (-1,1) are **orthogonal** (perpendicular) bc $\theta = \pi/2$ and $v \cdot w = 0$ (no alignment)

### Review: Many ways to express a dot product:

$$ d = \bar{v} \cdot \bar{w} = v^Tw = \Sigma_{i=1}^n v_i w_i = ||\bar{v}||_2||\bar{w}||_2 \cos \theta$$

In [5]:
# Compute the angle between vectors v = [10, 9, 3] and w = [2, 5, 12]
from numpy import arccos, dot

v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = \
    arccos(dot(v, w.T)/(norm(v)*norm(w))) # w.T to match inner dims, norm() default is L2
print(theta)

[[0.97992471]]


### Vector cross product

Geometric interpretation: <mark>A vector perpendicular to both $v$ and $w$, whose length equals the area enclosed by the parallelogram created by the two vectors</mark>

- Cross product definition: $v \times w = \Vert v \Vert_{2}\Vert w \Vert_{2}\sin{(\theta)} n \quad$, where:
    - $\theta$ can by computed via dot product
    - $n$ is a vector perpendicular to both $v$ and $w$ of unit ($1$) length

In [6]:
# Compute the cross product of v = [0,2,0] and w = [3,0,0]
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v,w))

[[ 0  0 -6]]


### Linear Combinations

- A **linear combination** of set $S$ is defined as $\Sigma \alpha_i s_i$
    - Here $\alpha_i$ values are the **coefficients** of $s_i$ values
    - Example: Grocery bill total cost is a linear combination of items purchased:
        - $\displaystyle{\sum c_i n_i}$ ($c_i$ is item cost, $n_i$ is qty. purchased)
    
### Linear Dependence and Independence
    
- A set is **linearly INdependent** if no object in the set can be written as a lin. combination of the other objects in the set.
    - Example: $v = [1, 1, 0], w = [1, 0, 0]$ and $u = [0, 0, 1]$ are <mark>linearly independent. Can you see why?</mark>
- Below is an example of a **linearly DEpendent** set. $x$ is dependent on 

In [7]:
# Writing the vector x = [8, -1, 4] as a linear combination of 3 vectors, v, w, and u:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])

x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]


## Matrices

These are $\mathbb{R}^{m\times n}$ objects.

### Length: 

If you treat the $m \times n$ elements of $M$ as an $mn$-dimensional vector, the $p$-norm of that vector is:

$\Vert M \Vert_{p} = \sqrt[p]{(\sum_i^m \sum_j^n |a_{ij}|^p)}$

### Addition and scalar multiplication

Same mechanics as for vectors

### Matrix multiplication (use `np.dot(P,Q)` to multiply)

The inner matrix dimensions of the two matrices (e.g. $P$ and $Q$) must match. 
- $P$ is of dimension $\mathbb{R}^{m \times p}$
- $Q$ is of dimension $\mathbb{R}^{p \times n}$ 
- Here, the dimension of size $p$ is the **inner matrix dimension**. 
    - If they match, it means # columns in $P$ equals # rows in $Q$.
- Dimensions $m$ and $n$ are the **outer matrix dimensions**. Thus each element of $M$ can be computed as:

$$M_{ij} = \sum_{k=1}^p P_{ik}Q_{kj}$$

In [8]:
# Multiply P=[[1,7],[2,3],[5,0]] and Q=[[2,6,3,1],[1,2,3,4]] -> [3x2] * [2x4] = output [3x4]

P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print(P)
print(Q)
print(np.dot(P, Q)) # <-- inner dimensions match (p=2). output is a [3x4] matrix
np.dot(Q, P) # <-- inner dimensions don't match ...4] * [3...; Error

[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

## Square matrices

- Dimension $n \times n$
- The **Determinant**, $det(M)$, is an important property of square matrices.
- For a $2 \times 2$ matrix; $det(M)$ is:
$$
\begin{split}
|M| = \begin{bmatrix}
a & b \\
c & d\\
\end{bmatrix} = ad - bc\end{split}
$$


- For a $3 \times 3$ matrix; $det(M)$ is:

$$
\begin{split}
\begin{eqnarray*}
|M| = \begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{bmatrix} & = & a\begin{bmatrix}
\Box &\Box  &\Box  \\
\Box & e & f \\
\Box & h & i \\
\end{bmatrix} - b\begin{bmatrix}
\Box &\Box  &\Box  \\
d & \Box & f \\
g & \Box & i \\
\end{bmatrix}+c\begin{bmatrix}
\Box &\Box  &\Box  \\
d & e & \Box \\
g & h & \Box \\
\end{bmatrix} \\
&&\\
& = & a\begin{bmatrix}
e & f \\
h & i \\
\end{bmatrix} - b\begin{bmatrix}
d & f \\
g & i \\
\end{bmatrix}+c\begin{bmatrix}
d & e \\
g & h \\
\end{bmatrix} \\ 
&&\\
& = & aei + bfg + cdh - ceg - bdi - afh
\end{eqnarray*}\end{split}
$$

- For higher dimension matrices, a similar approach can be used.

### Identity matrix

- A square matrix, $I$, with **ones on the diagonal** and **zeros everywhere else**
- Multiplying a matrix with $I$ (of compatible dimensionality) will produce the same matrix (like how $n \times 1 = n$)

In [9]:
# Find the determinant of M, and multiply M by np.eye(4) to show M x I = M

from numpy.linalg import det

M = np.array([[0,2,1,3], 
             [3,2,8,1], 
             [1,0,0,3],
             [0,3,2,1]])
print('M:\n', M)

print('Determinant: %.1f'%det(M))
I = np.eye(4)
print('I:\n', I)
print('M*I:\n', np.dot(M, I))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


## Matrix inverse

For square matrices ($\mathbb{R}^{n\times n}$), $M^{-1}$ is the inverse of $M$ if $M \cdot M^{-1} = I$ (like how $3 \times \frac{1}{3} = 1$)

- A matrix is **invertible** if it has an inverse
- The inverse of a matrix is unique: An invertible matrix **only has one inverse**.
- For a $2 \times 2$ matrix, the inverse is:
$$
\begin{split}
M^{-1} = \begin{bmatrix}
a & b \\
c & d\\
\end{bmatrix}^{-1} = \frac{1}{|M|}\begin{bmatrix}
d & -b \\
-c & a\\
\end{bmatrix}\end{split}
$$


### Is it invertible?

- **Singular matrices** are those which have **no inverses** (like how 0 has no inverse)
    - $det(M) = 0$
- **Nonsingular matrices** are those which **do have an inverse**
    - $det(M) \ne 0$

In [10]:
# Recall, M has non-zero determinant so is invertible; but det(P)=0 so it can't be inverted

from numpy.linalg import inv


print('Determinant: %.1f'%det(M))
print('Inv M:\n', inv(M))

P = np.array([[0,1,0],
              [0,0,0],
              [1,0,1]])
print('det(p):\n', det(P))
print('Inv P:\n', inv(P)) # <-- Error thrown because P is Singular (non-invertible)

Determinant: -38.0
Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
det(p):
 0.0


LinAlgError: Singular matrix

### Ill-Conditioned Matrices

- An ill-conditioned matrix is one which is **close to being singular** 
    - Its determinant will be close to 0 (problematic in the same way dividing by a tiny number is)
    - Computation errors (overflow, underflow, round-off errors) may occur
- **Condition number**: ***Higher number*** means the matrix is ***more*** ill-conditioned (i.e. closer to being singular)

### Trace 

- The **trace** of $A : A \in \mathbb{R}^{n\times n}$ is the sum of elements on the main diagonal (from left to right):

$$ \text{tr}(A) = \sum_{i=1}^{n} a_{ii} $$


## Back to non-square matrices

### Rank

- The **rank** of $A : A \in \mathbb{R}^{m\times n}$ is the **number of linearly independent columns or rows** in $A$
    - NB: Num. of lin. indep. cols. in a matrix $\equiv$ Num. of lin. indep. rows in that matrix

#### "Full Rank" Matrix

- $A$ is **full rank** if $\text{rank}(A) = \min(m,n)$
- $A$ is also full rank if **all its columns are linearly independent**

#### Augmented Matrix

- If vector $y$ is concatenated to matrix $A$, we say "$A$ augmented with $y$".
    - if $\text{rank}([A,y]) = \text{rank}(A)+1$, then vector $y$ is **"new" information**
    - otherwise it means $y$ can be created as a linear combination of the columns in $A$



In [11]:
# Compute the condition number and rank for matrix A = [[1,1,0],[0,1,0],[1,0,1]]
# If y = [[1],[2],[1]], get the augmented matrix [A,y]

from numpy.linalg import cond, matrix_rank
from numpy import trace

A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])

print('Condition number: ', cond(A))
print('Rank: ', matrix_rank(A))
print('Trace: ', trace(A))
y = np.array([[1], [2], [1]])
print(A.shape, y.shape)
A_y = np.concatenate((A,y), axis=1)
print('Augmented matrix:\n', A_y)

Condition number:  4.048917339522305
Rank:  3
Trace:  3
(3, 3) (3, 1)
Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]
